### ISSUE TITLE
initialValue (config to disable prase value from input value attribute)

### ISSUE THREAD

**Issue by genzographics** [babakhani/pwt.datepicker#101]
مشکل اینجاست که ظاهرن این کلاس فرضش بر اینه که تاریخ پیش فرض کنترل فرمی که ما میخوایم انتخابگر تاریخ رو بهش متصل کنیم همیشه میلادیه در صورتی که اینطور نیست.

با تعریف کردن یک گزینه تنظیمی جدید، میتونیم از تبدیل کردن تاریخ پیش فرض فرم موقع بارگذاری صفحه جلوگیری کنیم.

**Comment by babakhani** [comment]
تاریخ پیش فرض رو به سادگی میلادی در نظر بگیرید.
با توجه به اینکه تاریخ ها در بانک اطلاعاتی به صورت میلادی ذخیره می شود بهتر است ورودی و خروجی های انتخاب گر تاریخ میلادی باشند.

**Comment by genzographics** [comment]
رضا جان حرف شما در مورد ورودي و خروجي پايگاه داده ها كاملن درسته اما مشكل اساسي اونجايي پيدا ميشه كه محتواي يك فرم كه از طريق بارگذاري دوباره صفحه ثبت شده، نامعتبر شناخته بشه و فرم دوباره با همون محتواي قبلي ايجاد بشه. در اين صورت همون تاريخ جلالي كه تقويم قبلن انتخاب كرده بوده، دوباره تبديل ميشه. 

من فكر نميكنم درست باشه كه ما از برنامه نويس انتظار داشته باشيم كه قبل از بارگذاري مجدد يك فرم با محتواي نامعتبر، تاريخ جلالي رو به تاريخ ميلادي تبديل بكنه. 

خوشحال ميشم نظر شما رو بدونم.

**Comment by babakhani** [comment]
@genzographics 
این مدت در حال لانچ یه پروژه بودیم و کارهای اینجا عقب افتاد
قطعا هر موردی که پیشنهاد بدین از جمله این مورد رو انجام خواهیم داد.
دیگه فقط بستگی به زمان داره تا بتونیم این امکانات رو اضافه کنیم.

**Comment by masoud-vatandoost** [comment]
سلام مهندس کار خیلی خوبی انجام دادی ولی من هم همین مشکل رو دارم . کارهای جدید کی ریلیز میشه؟

**Comment by masoud-vatandoost** [comment]
آقای باباخانی با اجازتون من توی کدهاتون یه دستی بردم و برای استفاده خودم تابع اینیت رو تغییر دادم و این مشکل رو حل کردم شاید به صورت موقت مشکل بقیه حل بشه

`
init: function () {
            //console.error('hi');
            var self = this;
            var old = self.inputElem.val();
            if (old != '') {
                var p0 = old.split(' ');
                var p = p0[0].split('-');
                if (p0[1] != undefined) {
                    var p1 = p0[1].split(':');
                } else {
                    var p1 = '0:0'.split(':');
                }
                var date = new persianDate([+p[0], +p[1], +p[2], +p1[0], +p1[1]]);
                var formatted = moment(date.valueOf()).format(this.format);
                this.inputElem.val(formatted);
            } else {
                var formatted = moment().format(this.format);
                this.inputElem.val(formatted);
            }

            this.state = new State({datepicker: self});
            this.compatConfig();
            this._defineOnInitState();
            this._updateInputElement();
            this.view = this.views['default'];
            this.view.render(this);
            this.inputElem.data("datepicker", this);
            this.inputElem.addClass(self.cssClass);
            this._attachEvents();
            return this;
        }
`

**Comment by babakhani** [comment]
@masoud-vatandoost  ممنون از شما این مشکل رو در نسخه آینده حل خواهیم کرد.

**Comment by babakhani** [comment]
After v1.0.0 we have "initialValueType". accept 'persian', 'gregorian'. 
Also for reminding, initial value accept [ISO 8601](https://www.w3.org/TR/NOTE-datetime) (Currently, we support only date part, we will implement ISO 8601 in next minor version).
sample:
 `
input datepicker:
<input value="1396-10-12" />

inline datepicker
<div data-date="1396-10-12" />
`
see [example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype)
