### ISSUE TITLE
Date Range Selector

### ISSUE THREAD

**Issue by AmirNorouzpour** [babakhani/pwt.datepicker#102]
سلام
در ابتدا تشکر میکنم از زحمات روی این کتابخانه کامل
سوالم این بود که آیا این تقویم قابلیت انتخاب بازه تاریخ(range date selection)
روی یک تقویم رو داره؟
مثل: [https://github.com/longbill/jquery-date-range-picker](url)
ممنون میشم راهنمایی کنید
@babakhani

**Comment by babakhani** [comment]
درود فراوان
در حال حاضر این امکان وجود نداره شما می تونید به سادگی از دو انتخابگر استفاده کنید.

**Comment by babakhani** [comment]
Duplicate #49
