### ISSUE TITLE
مقدار بعد از submit

### ISSUE THREAD

**Issue by saeedsalehi1** [babakhani/pwt.datepicker#105]
سلام
تشکر می کنم از کار خیلی تمیزی که کردین
من از کامپوننت شما توی انگولار استفاده می کنم
مشکل اینه که بعد از submit مقدار به صورت unix ارسال می شه
راهی هست که بتونم همون مقدار انتخاب شده رو به صورت استرینگ بفرستم سمت سرور؟
و این که مقدار اولیه می تونه فارسی باشه؟
تا اونجا که توی issue ها دیدم ظاهرا این امکان وجود نداره

**Comment by babakhani** [comment]
Hi
you can use "formatter" and "altFieldFormatter", like this [example](http://jsfiddle.net/babareza/z3G2q/).
