### ISSUE TITLE
مشکل در هنگام back 

### ISSUE THREAD

**Issue by M0H3N** [babakhani/pwt.datepicker#106]
با سلام 
من تاریخ رو از دیتابیس در مقدار اینپوت ست میکنم بار اولی که صفحه لود میشه درست نشون داده میشه ولی اگه طرف بره یه صفحه دیگه و با مرورگر بک بزنه برگرده کلا تاریخو اشتباه نشون میده 
مشکل از چیه ؟

**Comment by kambizzandi** [comment]
این مشکلو منم دارم . برمیگرده به جایی که در js اگر تاریخ ورودی داشته  باشیم، اول اونو به جلالی برمیگردونه
چون پیش فرض اینه که تاریخ ورودی میلادی باشه
اینجا یکمی مساله ایجاد شده و باید درست بشه

**Comment by akoSalman** [comment]
آقا این مشکل رو برطرف کنید خواهشا
منم وقتی مقدار تاریخ رو از دیتابیس میگیرم و و مقدار جلالی شده آن را دوباره میزارم تو اینپوت یه عددای عجیب و غریب نشون میده و اون مقداری رو که باید نشون بده نیست.

**Comment by M0H3N** [comment]
به اینپوتش اینو اضافه کنید حل میشه :
autocomplete="off"

**Comment by babakhani** [comment]
Thanks @M0H3N . currently we work on 0.5.0. this issue will be fixed in this version.
