### ISSUE TITLE
غیر فعال سازی تاریخ ها به اشتباه

### ISSUE THREAD

**Issue by wolfmajid** [babakhani/pwt.datepicker#108]
سلام
خط 1609 کدتون جای عبارات داخل شرط ایف و الس باید عوض بشه
ممنون میشم عوض کنید و نسخه جدیدبدید
 if (thisUnix >= self.minDate && thisUnix <= self.maxDate) {
                                $(this).removeClass(self.cssClass.disbaled);
                            } else {
                                $(this).addClass(self.cssClass.disbaled); 
                            }

**Comment by pylover** [comment]
Could you please fork & send a pull request?

**Comment by babakhani** [comment]
This bug fixed in Develop version. currently we work on new version 0.5.0.
