### ISSUE TITLE
  .pDatepicker("setDate",[1392,12,1,11,11] ); مشکل نوع داده

### ISSUE THREAD

**Issue by mh69hedayati** [babakhani/pwt.datepicker#111]
`$( ".selector" ).pDatepicker("setDate",[1392,12,1,11,11] ); `
در این متد تمام آرگومان ها دریافتی از نوع استرینگ است به جز ارگومان روز 
` pDatepicker("setDate",[YYYY,MM,DD,h,m,s] ); `
 که برای رفع باگ  باید از تابع 
`parseInt(DD)`
استفاده شود
با تشکر از زحمات همه

**Comment by pylover** [comment]
Its not clear, please provide what you tried out, what you expected and what get
