### ISSUE TITLE
نمایش زمان 24 ساعته

### ISSUE THREAD

**Issue by ElnazIghani** [babakhani/pwt.datepicker#112]
با سلام
آیا  همچنان در تقویم ایجاد شده قابلیت استفاده از فرمت 24 ساعته وجود ندارد؟
در بین آپشن های موجود تنها می توان توسط 
 showMeridian: false  
قبل و بعداز ظهر را حذف کرد، اما در شرایطی که امکان نمایش 24 ساعته در
 plot area
 وجود نداشته باشد، در برخی کاربردها، عملا با مشکل مواجه می شویم
با تشکر

**Comment by pylover** [comment]
Welcome to github.
