### ISSUE TITLE
تغییر مقادیر انتخاب شده زمان و تاریخ با استفاده از تغییر مستقیم در inputو عدم استفاده از انتخابگر 

### ISSUE THREAD

**Issue by amirfahmideh** [babakhani/pwt.datepicker#113]
سلام دوست عزیز 
با تشکر از زحماتی که روی تقویم فارسی کشیدی و انصافاً کار خوبی هم شده 
من تقویم شما  رو توی یک پلاگین اختصاصی روی پروژه asp.net core دارم شخصی سازی می کنم فقط  یک مشکل دارم که نتونستم توی مستندات روی سابت پیداش کنم ممنون می شم اگه راهنمایی بکنید. 

بعد از اینکه کاربر با استفاده از پلاگین تقویم اقدام به انتخاب تاریخ و زمان می کنه متن داخل input اون زمان انتخاب شده را مشخص می کند که خوب من از altField ها استفاده میکنه که ایده فوقالعاده ای بوده و من رو توی پیاده سازی این کنترل شخصی سازی شده خیلی کمک کرده حالا سوال اینجاست که با اینکه من Observer رو True کردم اما می خوام وقتی کاربر اقدام به تغییر تاریخ از روی input بکنه مقدار altField ها و به همون نسبت مقدار انتخاب شده انتخابگر تاریخ و زمان هم تغییر کنه که خوب من از روی مستندات چیزی متوجه نشده 

ممنون می شم راهنماییم کنید.

**Comment by babakhani** [comment]
درود 
متن خوانا نیست
لطفا متن صحیح به همراه نمونه کد وارد کنید تا بتونم کمک کنم
شاد باشید

**Comment by nimamsv** [comment]
درسته متن خوانا نیست اما فکر میکنم مشکل من هم همینه
زمانیکه با پیکر تکس باکس آپدیت میشه تاریخ ثبت میشه اما سمت سرور چیزی ارسال نمیشه من فکر مسکنم دی او ام آپدیت نمیشه با جی کوری زمانی دیتا ثبت میشه که بعد از انتخاب دیت با پیکر اینتر زدا بشه یا روی خود تکس باکس مجددا کلیک کنید.
اگه ممکنه راهنمایی بفرمایید
