### ISSUE TITLE
مشکل در قسمت نمایش جهت ها

### ISSUE THREAD

**Issue by porya0ras** [babakhani/pwt.datepicker#115]
بدلیل نمایش نا مناسب جهت های هدایتی 
![2017-03-18 12_53_01-persian datepicker](https://cloud.githubusercontent.com/assets/10659073/24070836/0651daea-0bda-11e7-9f54-9b6aa7409ee1.png)

لطفا از جهت های آیکون برای نمایش جهت ها استفاده کنید.
من از موارد زیر استفاده کردم و خیلی بهتر شد
`<i class="fa fa-chevron-right" aria-hidden="true"></i>`
`<i class="fa fa-chevron-left" aria-hidden="true"></i>`
![2017-03-18 13_02_40- _](https://cloud.githubusercontent.com/assets/10659073/24070903/52cd138e-0bdb-11e7-9515-dbe35453b300.png)

**Comment by fadakar** [comment]
use navigator like this
`$('#date_from').persianDatepicker({
                altField: '#alt_date_from',
                format: 'YYYY/MM/DD',
                navigator: {
                    enabled: true,
                    text: {
                        btnNextText: ">",
                        btnPrevText: "<"
                    },
                },
            });
`

**Comment by hmdhasani** [comment]
you can fix that by this css:

/* Correct persiann date picker nav buttons text*/
.datepicker-header > .btn-next, .btn-prev {
    direction: ltr;
}

**Comment by babakhani** [comment]
Thanks @fadakar @hmdhasani for answer this question.
