### ISSUE TITLE
مشکل تاریخ در modal

### ISSUE THREAD

**Issue by moslem68** [babakhani/pwt.datepicker#116]
سلام برا ویرایش اطلاعاتم از modal استفاده کردم و از کد زیر برای نمایش datapicker.  اما موقع focus مقدار تاریخ تغییر میکنه و درست نمایش داده نمیشه.
$(document).on('focus', '#myModal #Date', function () {
    $("#myModal #Date").pDatepicker({
        format: 'YYYY/MM/DD'
    });
})

**Comment by MAliM1988** [comment]
Hello every one you can fix that problem with this Style

<style>
	.datepicker-plot-area {
		z-index: 1151 !important;
	}
</style>

**Comment by babakhani** [comment]
@MAliM1988  thanks for answer.
