### ISSUE TITLE
input value convert to wrong date

### ISSUE THREAD

**Issue by ghost** [babakhani/pwt.datepicker#117]
Hello,
When I use:
<input type="text" class="form-control" id="finish" name="finish" placeholder="پایان" value="1395/12/30" dir="ltr" />
The input become 774/10/09 which is wrong date.
My config to use datepicker is:
$("#finish").pDatepicker({format:"YYYY/MM/DD"});

**Comment by ElnazIghani** [comment]
By default, date-picker uses Gregorian date (DateTime.Now). If you want to use Persian date as value, use `setDate()` method. Maybe you have used wrong default value (it happens mostly in post-backs)

**Comment by babakhani** [comment]
@ElnazIghani Thanks.
