### ISSUE TITLE
عدم آپدیت شدن تاریخ انتخاب شده در دیت پیکر، بر اساس تاریخ تکس باکس

### ISSUE THREAD

**Issue by ElnazIghani** [babakhani/pwt.datepicker#118]
با سلام
آیا 
feature
ی وجود دارد که با ست کردن آن، به محض تغییر تاریخ در تکس باکس بصورت دستی، تاریخ انتخاب شده دیت پیکر هم تغییر کند؟
در حال حاضر متاسفانه با وجود تغییر تاریخ در اینپوت، تاریخ انتخاب شده دیت پیکر همان تاریخ قبلی باقی می ماند.

**Comment by mohamadaliakbari** [comment]
Hi
`observer` option do this.

**Comment by ElnazIghani** [comment]
But it works just if we use script for set the value, not with change the value in input textbox manually.

> if you use $(element).val() to set input val and 'observer : true' , datepicker sync with your inputed Value. Observer Watch input and altField Elemets.

**Comment by babakhani** [comment]
Hi guys, please check this beta version.
[http://babakhani.github.io/PersianWebToolkit/beta/datepicker](http://babakhani.github.io/PersianWebToolkit/beta/datepicker)

**Comment by ElnazIghani** [comment]
Hi,

Thanks for resolve the mentioned bug. In new beta version, there is a bug on months with 31 days, in date picker. (the 31th. day is omitted and we see two 1th. day for the next month )


________________________________
