### ISSUE TITLE
yyyy-mm-dd میلادی

### ISSUE THREAD

**Issue by danial9372** [babakhani/pwt.datepicker#119]
سلام
چطور میتونم وقتی تاریخ  انتخاب کردم
بصورت میلادی به این شکل yyyy-mm-dd
برگردونه؟
فقط برام تاریخ مهمه

**Comment by nimaa77** [comment]
سلام
`        formatter : function(unix){
            var date =  new Date(unix);
           	var date = date.toISOString().substr(0,10);
            return date;
        }`
تاریخ به صورت yyyy-mm-dd برمیگرده 
ولی خب از هیچی بهتره :)

**Comment by babakhani** [comment]
```javascript
formatter : function(unix){ 
  var date = new pDate(unix); 
  return date.format('YYYY-MM-DD')
}
```
