### ISSUE TITLE
در خواست اضافه کردن آیکن تقویم کنار تکست باکس

### ISSUE THREAD

**Issue by myasingh** [babakhani/pwt.datepicker#120]
سلام. می خواستم درخواست کنم اگه ممکنه یه آیکن تقویم کنار تکست باکس اضافه کنید که با کلیک روی اون تقویم باز بشه

**Comment by babakhani** [comment]
New version is under development.
this feature added in new version.
you can see last document and examples in this link:
[http://babakhani.github.io/PersianWebToolkit/docs/datepicker/](http://babakhani.github.io/PersianWebToolkit/docs/datepicker/)
also you can use last beta version by 
`npm i persian-datepicker@0.5.3`
