### ISSUE TITLE
فراخوانی یک رویداد در زمانی که یک تقویم inline برای اولین بار نمایش داده میشه

### ISSUE THREAD

**Issue by bahmansh** [babakhani/pwt.datepicker#121]
سلام
من میخوام در موقع نمایش تقویم روزهای تعطیل و مناسبت های تاریخی رو در تقویم با یک رنگ خاص مشخص کنم (البته نمیخوام غیر فعال کنم)
در رویدادهای onNext و onPrev با استفاده از پارامتر e که میگیرن این کار خیلی راحت انجام میشه
موقع نمایش (loading) هم رویدادی هست که با این پارمتر فراخوانی بشه؟

onNext:function(e)
                {
                    var dayView = e.datepicker.container.dayView[0];
                    var headers = $(dayView).find(".header-row-cell");                    
                    $(headers[6]).css("background-color", "red");
                    $(headers[5]).css("background-color", "red");
                    var tableDays=$(".table-days");
                    console.log(tableDays);
				},

ممنون

**Comment by babakhani** [comment]
لطفا سوالتون رو بهتر مطرح کنید.
سعی کنید یه پروژه نمونه روی لینک زیر بسازید
jsfiddle.net
