### ISSUE TITLE
Issue with min/max date

### ISSUE THREAD

**Issue by mohammad-hth** [babakhani/pwt.datepicker#122]
سلام
من میخوام برای تاریخ محدودیت تعیین کنم. برای مثال فقط از امروز به بعد قابل انتخاب باشه و قبل از اون غیر فعال باشه. [مثل این مثال](https://jqueryui.com/datepicker/#min-max)

واسه این کار از
 `minDate:1496146928` 
استفاده کردم ولی کل تاریخ ها رو غیر فعال کرد

چطور باید این کار رو انجام بدم؟

**Comment by mohammad-hth** [comment]
کسی جوابی واسه این سوال نداره؟

**Comment by babakhani** [comment]
درود
این ویژگی روی نسخه ۰.۴.۵ مشکلاتی داره. لطفا آخرین نسخه بتا رو روی آدرس زیر چک کنید.
babakhani.github.io/PersianWebToolkit/beta/datepicker

**Comment by babakhani** [comment]
duplicate #94
