### ISSUE TITLE
minDate and maxDate problem

### ISSUE THREAD

**Issue by skmohammadi** [babakhani/pwt.datepicker#124]
سلام.
آقای باباخانی عزیز چرا من وقتی یک تقویم رو به صورت زیر فراخوانی میکنم تاریخ های مشخص شده **غیرفعال** میشن؟
`$("#to").pDatepicker({
	minDate: 1496777400000,
	maxDate: 1496950200000
});`
میخوام بازه زمانی قابل انتخاب 17 الی 10 خرداد باشه.

**Comment by mohammad-hth** [comment]
من هم همین مشکل رو دارم

**Comment by babakhani** [comment]
درود
این ویژگی روی نسخه ۰.۴.۵ مشکلاتی داره. لطفا آخرین نسخه بتا رو روی آدرس زیر چک کنید.
[babakhani.github.io/PersianWebToolkit/beta/datepicker](babakhani.github.io/PersianWebToolkit/beta/datepicker)

روی آدرس زیر در تماس باشید.
[https://gitter.im/persianwebtoolkit/datepicker](https://gitter.im/persianwebtoolkit/datepicker)

**Comment by babakhani** [comment]
duplicate #94

**Comment by skmohammadi** [comment]
سلام. این آدرس رو بررسی کردم. مشکل همچنان برقراره

babakhani.github.io/PersianWebToolkit/beta/datepicker

**Comment by babakhani** [comment]
لطفا لینک زیر رو ببینید من یه مثال براتون آماده کردم.
https://jsfiddle.net/po2fzn2n/
