### ISSUE TITLE
mousewheel تابع

### ISSUE THREAD

**Issue by makantayebi** [babakhani/pwt.datepicker#125]
این تابع قدیمی شده است. و با JQuery v3.1.1 به مشکل برمی خورد.
پیشنهاد:
https://stackoverflow.com/questions/8189840/get-mouse-wheel-events-in-jquery

**Comment by babakhani** [comment]
Thanks for report. i will check this.

**Comment by makantayebi** [comment]
اگر این به معنای این هست که تصحیح نمی فرمایید بنده سر فرصت انجام خواهم داد.

**Comment by babakhani** [comment]
این تابع به کلی جایگزین شده است.
