### ISSUE TITLE
(latest beta version): Problem in showing the day of months with 31 days.

### ISSUE THREAD

**Issue by ElnazIghani** [babakhani/pwt.datepicker#126]
Hi, in the beta version, instead of 31th. day of the month we have 01, and again another 01 is repeated for next month.
thank you

**Comment by babakhani** [comment]
Thank you for taking the time.
![Uploading Screen Shot 1396-03-28 at 9.33.13 PM.png…](as you can see, 31th day of month is render as well)
If it's possible for you, send me screenshot or give me more details.

**Comment by ElnazIghani** [comment]
________________________________
