### ISSUE TITLE
مشکل فرمت بندی

### ISSUE THREAD

**Issue by mohamamd-chavoshipor** [babakhani/pwt.datepicker#130]
سلام خسته نباشید
ببخشید من وقتی از 
استفاده میکنم تو input تو حالت اول اینجوری چاپ میشه:
775-01-25
اگه گزینه" امروز" رو انتخاب کنم درست میشه اما خو نمیخوام اینجوری باشه 
اگه هم format
رو پاک کنم که تاریخ با ساعت رو نشون و درست نشون میده
میشه بگید مشکل از کجاست؟
`            $("#date_picker").pDatepicker({
                format: "YYYY-MM-DD",
                maxDate: new Date(),
                minDate: 1,
                autoClose:true,
                todayHighlight: true
            });`

@babakhani

**Comment by babakhani** [comment]
@mohamamd-chavoshipor 
تاریخی که در اینپوت اضافه می کنید باید به میلادی باشه
