### ISSUE TITLE
How can i find an example that shows inline persian date picker?

### ISSUE THREAD

**Issue by bobper** [babakhani/pwt.datepicker#133]
Hi  
It's not an issue  , Its just a request for an example for inline persian date picker
I want to use inline date-picker but i couldn't found that the example 
Thanks.

**Comment by babakhani** [comment]
stable 0.4.5 version example:
http://jsfiddle.net/DqppC/146/

new 0.5.* beta version document: http://babakhani.github.io/PersianWebToolkit/beta/datepicker/example/
you can install new beta version with:
npm install persian-datepicker@beta

**Comment by babakhani** [comment]
New version released.
example for this question: http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#inline-example
