### ISSUE TITLE
ساخت دو فیلد با تاریخ های مرتبط به هم (تاریخ آغاز و پایان)

### ISSUE THREAD

**Issue by ahasani194** [babakhani/pwt.datepicker#134]
با سلام و عرض تبریک بابت ماژول ساخته شده
می خواستم بدونم که با این ماژول می تونیم 2 تا فیلد مرتبط به هم داشته باشیم به صورتی که تاریخ انتخابی فیلد اول minDate تاریخ دوم رو ست کنه؟

**Comment by ahasani194** [comment]
تو ماژول های دیگه این امکان به صورت زیر برقرار شده است که با استفاده از متود آپشن میتونیم کمینه فیلد دیگر رو تغییر بدیم

        $(".activeDate").datepicker({
            minDate: 0,
            maxDate: "+1Y",
            formatt: "yyyy/mm/dd",
            isRTL: true,
            changeMonth: true,
            changeYear: true,
            onSelect: function (date) {
                var dateObject = $(this).datepicker('getDate');
                $(".expireDate").datepicker("option", { minDate: dateObject });
            },
        });

**Comment by babakhani** [comment]
@ahasani194 i think we can support this in new 0.5.* version.
read new document.
http://babakhani.github.io/PersianWebToolkit/beta/datepicker/

**Comment by ahasani194** [comment]
thank you for answer and special thanks for your great plugin
Good luck
