### ISSUE TITLE
probably a bug in minutestep

### ISSUE THREAD

**Issue by sadeg** [babakhani/pwt.datepicker#136]
After I used minutestep, the minute selector goes higher than 60 :
![s](https://user-images.githubusercontent.com/7746557/28751302-6c84218a-7519-11e7-9d03-25cb185bbaf0.png)

javascript :
```
    $("#time").persianDatepicker({
        format: "HH:mm a",
        onlyTimePicker: true,
        observer: true,
        timePicker: {
            minuteStep: 15,
            showSeconds: false
        }
    });
```

**Comment by babakhani** [comment]
thanks for report.
new version released. check this out and if your problem didn't solved reopen this issue.
