### ISSUE TITLE
pd.setDate is not a function

### ISSUE THREAD

**Issue by mmehdibalouchi** [babakhani/pwt.datepicker#137]
I am using beta version but still have this error

**Comment by mmehdibalouchi** [comment]
I think the bug is in this part of code
`if (dp && typeof tempArg[0] === "string") {
                funcName = tempArg[0];
                output = dp[funcName](tempArg[0]);`

and `dp[funcName](tempArg[0])` should convert to `dp[funcName](tempArg[1])`
but without change you can use it this way:
`pd = $(this.$el).find('input').pDatepicker(this.options);
pd.pDatePicker.setDate(val);`

**Comment by babakhani** [comment]
thanks for the report,
I can't understand your problem, could you give more example.

**Comment by babakhani** [comment]
finally, i got it :) #154

**Comment by babakhani** [comment]
Fixed on version 1.0.0
Check this out.
