### ISSUE TITLE
مشکل Set کردن دیتا

### ISSUE THREAD

**Issue by parisan1986** [babakhani/pwt.datepicker#138]
# با سلام
من نمیدونم چطور میتونم تاریخ انگلیسی که از سمت سرور میاد در datepickeram قرار بدم
و همچنین نمیدونم چطور مقدار خالی در datepickeram قرار بدم
کلا با Set کردن دیتا مشکل دارم

**Comment by babakhani** [comment]
there are many example here
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/
