### ISSUE TITLE
Datepicker is not loading

### ISSUE THREAD

**Issue by goorgoor** [babakhani/pwt.datepicker#140]
Hi,

I'm trying to change an existing datepicker from enlgish to persian. 

Here is the old datepicker's script. 
`<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>`

And it was called by 

`                      <input type="text" name="news_date" id="datepicker" value="" class="form-control">`

When i follow codes you see under, and remove the codes above, i dont get anything!:

```
<head>
  <link rel="stylesheet" href="css/persian.datepicker.css"/>
  <script src="js/jquery.js"></script>
  <script src="js/persian.date.js"></script>
  <script src="js/persian.datepicker.js"></script>
</head>

<script type="text/javascript">
  $(document).ready(function() {
  $(".example1").pDatepicker();
  });
</script>
```

and this

`
<input type="text" class="example1" />
`

**Comment by babakhani** [comment]
This can have many reasons, can you provide more sample or online example?

**Comment by babakhani** [comment]
If you want to keep this up, I will serve.
