### ISSUE TITLE
Convert digits in input to persian digits

### ISSUE THREAD

**Issue by skmohammadi** [babakhani/pwt.datepicker#141]
Hi. How we can convert latin digits in input into Persian digits?

**Comment by PouriaParhami** [comment]
This way i think
https://github.com/babakhani/PersianDate#format-to-persian-date

**Comment by skmohammadi** [comment]
What is have asked?
Your desired way can change value of html input from English to Persian?

**Comment by PouriaParhami** [comment]
sorry about that.
do you see the example ?
https://github.com/babakhani/pwt.datepicker/blob/master/src/index.html
or demo ?
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/0.4.5/demo.html

$("#persianDigit").persianDatepicker({
            altField: '#persianDigitAlt',
            altFormat: "YYYY MM DD",
            persianDigit: false
        });

you do it and nothing happened?

**Comment by babakhani** [comment]
check new version document
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#persiandigit
