### ISSUE TITLE
آپدیت شدن تاریخ در input

### ISSUE THREAD

**Issue by aminweb2** [babakhani/pwt.datepicker#144]
با سلام
ما تاریخ جریمه دیرکرد قرار دادیم.
`observer: true,`
هست.
و input هم بصورت زیر 
` <input type="text" id="dbime" name="dbime" onclick="calcInsurance();" onchange="calcInsurance();">
`
اما بعد از ناتخاب تاریخ عمل نمی کنه بلکه باید مجدد موس رو روی اینپوت کلیک کنید و خارج بشی تا عمل کنه.
ممنون میشم راهکاری اگر هست بفرمایید.
سپاس

**Comment by babakhani** [comment]
@aminweb2 
درود فراوان متاسفانه متوجه مشکل شما نمی شم. اگر امکان داره مثال و یا توضیحات بیشتری بدین تا بتونم کمکتون کنم.

**Comment by babakhani** [comment]
@aminweb2 
در صورتی که براتون امکانش بود توضیحات بیشتری بدین و یا برای بنده یک نمونه بسازید. خوشحال می شم این موضوع رو ادامه بدیم
در حال حاضر این مورد رو می بندم
