### ISSUE TITLE
Loading err

### ISSUE THREAD

**Issue by AmirhosseinBayat** [babakhani/pwt.datepicker#145]
Hi, first of all, tnx for your useful component
my problem is after set date on input and post to the server, convert solar date the Gregorian date and save on database, 
but after loading data for update action, I convert it to solar and put it to input field but the problem is when clicking on date-picker doesn't show date before I added in the system.
I set observer and it doesn't work could you help me to solve the problem.

**Comment by AmirhosseinBayat** [comment]
why when I use 0.5.5 Persian date-picker setDate it cause setDate is not a function();
this is my code: 
         var pd = $('#normal').persianDatepicker();
	pd.setDate(1382276091100);

and browser console is: 
![datepicker_err](https://user-images.githubusercontent.com/11735490/29560581-a701b648-8747-11e7-8295-921b4565a0f5.png)

**Comment by babakhani** [comment]
> I convert it to solar and put it to input field but the problem is when clicking on date-picker doesn't
this date picker currently only accepts the Gregorian date in input value.

**Comment by AmirhosseinBayat** [comment]
so how I can solve my problem, do you have any idea?

**Comment by babakhani** [comment]
@AmirhosseinBayat 

it's work properly

`<input id="datepicker" value="2017/02/02" >`

its convert to solar in date picker and you see the wrong date.

`<input id="datepicker" value="1396/02/02" >`

> I convert it to solar and put it to input field

simply don't convert to solar.

**Comment by AmirhosseinBayat** [comment]
Right! but when I put a Gregorian date on page loading and this put year and month correctly but doesn't  select the day.

![datepicker](https://user-images.githubusercontent.com/11735490/29856609-4d73e542-8d69-11e7-8331-0da442e9d687.png)

**Comment by babakhani** [comment]
do you have something like this in your config?

`initialValue: false`

if `initialValue` set `false` date picker didn't update inputs and doesn't select date in date picker, the functionality of this option has some issue, I fixed it on `fix-issues-on-0-5-5 branch`.
you must wait until the weekend that I planned to release a new version.

if you don't set `initialValue: false`, please give me more information about your config and initial html.

**Comment by AmirhosseinBayat** [comment]
So, I hope this weekend you release your new version.

    would you mind add me to the date-picker contributor, I like to develop this library

**Comment by babakhani** [comment]
@AmirhosseinBayat  new version 1.0.0 release. [check this out](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/).

> would you mind add me to the date-picker contributor? I like to develop this library

I will be very happy if you can help me with this. contact me on my email.
