### ISSUE TITLE
How to change date_picker region

### ISSUE THREAD

**Issue by AmirhosseinBayat** [babakhani/pwt.datepicker#146]
is there any way to change language or region of datepicker,
you know we need to change datepicker location when website language turns to English.
could you tell us how to do it?

**Comment by babakhani** [comment]
#76

**Comment by babakhani** [comment]
@AmirhosseinBayat  finally `persian-datepicker` support Gregorian date.

Check [Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#gregorian-calendar)
