### ISSUE TITLE
غیر فعال کردن تاریخ های قبل امروز

### ISSUE THREAD

**Issue by danial9372** [babakhani/pwt.datepicker#147]
سلام 
چطور میتونم تواسکریپت زیر تاریخ های قبل امروز غیر فعال کنم 
**فقط تاریخ های بعد امروز بشه انتخاب کرد**

```
 $("#jalaliDatePicker").pDatepicker({
        format: "YYYY-MM-DD",
        viewMode: "year",
        altField: "#jalaliToGregorian",
        altFieldFormatter: function (unix) {
            var date = new Date(unix);
            var date = date.toISOString().substr(0, 10);
            return date;
        }
    });

```

**Comment by babakhani** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#mindate

**Comment by babakhani** [comment]
@danial9372 
فکر می کنم مشکل شما با خواندن لینک بالا حل می شه در غیر اینصورت این مورد رو دوباره باز کنید
با آرزوی شادی
