### ISSUE TITLE
How to set date On loading date_picker

### ISSUE THREAD

**Issue by AmirhosseinBayat** [babakhani/pwt.datepicker#154]
why when I use 0.5.5 Persian date-picker setDate it cause setDate is not a function();
this is my code: 
         var pd = $('#normal').persianDatepicker();
	pd.setDate(1382276091100);

and browser console is: 
![datepicker_err](https://user-images.githubusercontent.com/11735490/29560581-a701b648-8747-11e7-8295-921b4565a0f5.png)

**Comment by babakhani** [comment]
@AmirhosseinBayat Fixed in version 1.0.0
Thanks for the report.
