### ISSUE TITLE
قابلیت ارتباط دو تقویم با هم

### ISSUE THREAD

**Issue by reza-hm89** [babakhani/pwt.datepicker#157]
چطور میشه دو تاریخ باهم به صورت تاریخ شروع و تاریخ پایان در ارتباط باشن؟؟ و تاریخ های قبل و بعد این دو قابل انتخاب نباشن

**Comment by babakhani** [comment]
در حال حاضر چنین امکانی در یک تقویم وجود ندارد
برای زمان شروع و پایان شما می توانید از دو تقویم استفاده کنید که هر تقویم امکان تنظیم شروع و پایان را داراست

**Comment by reza-hm89** [comment]
من در حال حاضر از دو تقویم استفاده می کنم. میخوام به صورتی باشه که max تقویم شروع مقدار تقویم پایان باشه و min تقویم پایان، مقدار تقویم شروع باشه.
بصورت داینامیک یک بار مقدار میگیره اما از سری دوم بهم میریزه!
چطور میتونم پلاگین  شما رو به صورت داینامیک destroy کنم و دوباره یک instance جدید به input انتساب بدم؟

**Comment by davodaslanifakor** [comment]
@babakhani  سلام بابک جان بهتره به نظرم این نمونه رو مثال بزنی من خیلی ها به این قضیه نیاز دارن

**Comment by babakhani** [comment]
@reza-hm89 @davodaslanifakor 
Currently, I didn't have any plan to implement range selector inside this project, you can use two instances. I add an example to docs. in this example we make sure 'to' date is after 'from' date and also 'from' is before 'to' date. 

[Eample](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#range-selector)
