### ISSUE TITLE
How to import this package when using webpack?

### ISSUE THREAD

**Issue by vfsoraki** [babakhani/pwt.datepicker#158]
I am trying to load this package inside my Vue project, which uses Webpack as bundler.

The steps I took, and failed:

Installed your package:

```
npm install --save persian-datepicker
```

Inside a component, none of these work:

```
import 'persian-datepicker'
# or
import 'persianDatepicker'
# or
require('persian-datepicker')
# or
require('persianDatepicker')
``` 

All of these result in module not being found.

I have solved it using the following (hackish) code inside my Webpack entry point:

```
var $ = require('jquery')
var pd = require('persian-date/dist/persian-date.min.js')
window.jQuery = $
window.$ = $
window.persianDate = pd
require('persian-datepicker/dist/js/persian-datepicker.js')
```

with this, everything is loaded globally, and I don't need more `import`s or `require`s.

but I feel this is not the right thing to do. I should be able to load it when I need, not globally.

**Comment by ykh** [comment]
no progress?!

**Comment by pooria-m** [comment]
The best workaround for this issue (by the plugin's developer) is to add a "main" key to `package.json` and point it to the distributed js file `(dist/js/persian-datepicker.js)`.

**Comment by mortadda** [comment]
import persianDate from 'persian-date'
window.persianDate=persianDate;
import  'persian-datepicker/dist/js/persian-datepicker.min.js'
