### ISSUE TITLE
محدود کردن انتخاب کاربر

### ISSUE THREAD

**Issue by poorali** [babakhani/pwt.datepicker#160]
سلام 
آیا در  ورژن فعلی امکان محدود کردن انتخاب کاربر وجود دارد  ؟
 به طور مثال : تاریخ های قبل از امروز قابل انتخاب نباشند

**Comment by rezaya2938** [comment]
قبلا هم بود. ولی مشکل داشت(ورژن0.4.5) الان اصلاح شده. با
minDate , MaxDate
انجام بدید.
مثال برا امروز تا 10 روز بعد
`var d = new Date();
d.setDate(d.getDate() - 1); 
var startDay = parseInt(d.getTime());
d.setDate(d.getDate() +10);
var endDay = parseInt(d.getTime());
$(".datepickerfa").pDatepicker({
    format: 'YYYY/MM/DD',
    navigator: false,
    autoClose: true,
    maxDate: endDay,
    minDate: startDay
});`

**Comment by babakhani** [comment]
[example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#mindate)
