### ISSUE TITLE
تاریخ میلادی

### ISSUE THREAD

**Issue by heidarymr** [babakhani/pwt.datepicker#161]
سلام
ایا این امکان وجود دارد که در input تاریخ میلادی برگردد؟

**Comment by heidarymr** [comment]
مثلا با استفاده از 
formater

**Comment by babakhani** [comment]
yes, see [example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#formatter)

**Comment by heidarymr** [comment]
مثلا من الان اگر بخام تقویم پاپ آپ شمسی باشه ولی مقداری که توی فیلد برمیگردونه میلادی باشه چه کدی باید استفاده کنم؟ مثالی که زدید به یونیکس برمیگردونه، توی مستندات هم توضیحاتی پیدا نکردم

**Comment by heidarymr** [comment]
سلام
؟؟؟

**Comment by babakhani** [comment]
درود
شما می تونید مقدار یونیکس رو به هر مقداری که می خواین تبدیل کنید

```javascript
$('.formatter-example').persianDatepicker({
    altFormatter: function(unix){
         return new Date(unix); 
    } 
});
```

**Comment by heidarymr** [comment]
سلام
من از کد زیر استفاده کردم

```
$("#sample").persianDatepicker({
    formatter: function(unix) {
        return moment.unix(unix/1000).format('YYYY-MM-DD HH:mm:ss');
    }
});

```
کد بالا بدون مشکل کار میکنه، مشکل زمانی هست که فیلد خودش تاریخ پیشفرض داره، به درستی توی پاپ آپ نمایش داده نمیشه
منظورم قبل از باز کردن پاپ آپ هست
