### ISSUE TITLE
پیشنهاد:سوئیچ با تقویم میلادی

### ISSUE THREAD

**Issue by heidarymr** [babakhani/pwt.datepicker#162]
امکان سوئیچ بین تقویم جلالی و میلادی
شبیه این:
http://amirkabirdataminers.github.io/ADM-dateTimePicker/

**Comment by babakhani** [comment]
added in v1.0.0 
see [example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#gregorian-calendar)

**Comment by heidarymr** [comment]
عالی
