### ISSUE TITLE
پیشنهاد: بهینه سازی ظاهر

### ISSUE THREAD

**Issue by heidarymr** [babakhani/pwt.datepicker#163]
سلام
چند خط کد جهت زیباتر شدن اینترفیس
.header-row-cell {
    color: #fc5f2a !important;
}

div#plotId {
    width: 280px !important;
    max-width: 100vw;
    min-height: 20em;
}

.header-row {
    border-bottom: 1px solid #eee;
    margin-bottom: 7px;
}

.datepicker-plot-area .datepicker-day-view .table-days td span.selected:hover, .datepicker-plot-area .datepicker-day-view .table-days td span:hover, .datepicker-plot-area .datepicker-year-view .year-item:hover, .datepicker-plot-area .datepicker-month-view .month-item:hover {
    background-color: #fee3da;
    color: #d63803;
}

.datepicker-plot-area .datepicker-day-view .table-days td span.selected:hover, .datepicker-plot-area .datepicker-year-view .year-item.selected:hover, .datepicker-plot-area .datepicker-month-view .month-item.selected:hover {
    text-shadow: none;
background: #fc5f2a !important;
    color: white !important;
    border-radius: 50%;
}
.datepicker-plot-area .datepicker-day-view .table-days td span.selected, .datepicker-plot-area .datepicker-year-view .year-item.selected, .datepicker-plot-area .datepicker-month-view .month-item.selected {
    text-shadow: none;
background: #fc5f2a !important;
    color: white !important;
    border-radius: 50%;
	
}
table.table-days {
    font-size: 16px;
}

.datepicker-plot-area .datepicker-time-view input {
    min-width: 10px !important;
}

.datepicker-plot-area .datepicker-day-view .table-days td span {
    width: 35px;
    height: 35px;
    line-height: 37px;
}

.datepicker-plot-area .datepicker-day-view .month-grid-box {

    margin-top: -7px;
}

.month-item,.year-item {
    width: 67px !important;
    height: 67px !important;
    line-height: 67px !important;
    margin:auto !important
}

.month-grid-box {
    height: auto !important;
}
![photo5906681687272696207](https://user-images.githubusercontent.com/3177460/30540843-087e6424-9c8e-11e7-8d4e-b50565456ee2.jpg)
![photo5906681687272696208](https://user-images.githubusercontent.com/3177460/30540844-08827618-9c8e-11e7-8c9b-0e8cf4171d84.jpg)
![photo5906681687272696209](https://user-images.githubusercontent.com/3177460/30540845-08837d7e-9c8e-11e7-82b5-3a99e5f99742.jpg)

**Comment by babakhani** [comment]
از شما بسیار سپاسگذارم اگر دوست داشتین می تونم کمک کنم تا این رو یک تم برای افزونه کنید و برای استفاده دیگر دوستان به اشتراک بگزارید
در نسخه اخر امکانات خوبی برای این کار اضافه شده.

**Comment by heidarymr** [comment]
سلام
من کدهای css را در همین تیکت ارسال کردم. شما زحمتشو بکشید روی اسکریپت اضافه کنید.

**Comment by babakhani** [comment]
ممنون از تلاش شما به نظر بنده اگر این کد به صورت یک تم برای افزونه اماده ارایه شود، بهتر است
اگر زمانبندی اجازه بده در فرصتی مناسب تم های جدید رو برای افزونه اضافه خواهیم کرد
از این که کارتون رو به اشتراک گزاشتین باز هم سپاسگذارم
