### ISSUE TITLE
Persian date-time to the equivalent Gregorian date-time

### ISSUE THREAD

**Issue by torgheh** [babakhani/pwt.datepicker#166]
We usually need to store dates in the western calendar format, meaning that before submitting a form we have to be able to convert the Persian date-time to the equivalent Gregorian date-time. 

Right now there is no easy way to do this. For example using `altField` is already complicated since you have to define a `formatter`, but the real problem comes when you have more than one date-time input and there is no way you can pragmatically define the `altField`.
You might suggest using `onSelect` event, but that event doesn't cover the time change or manual changes to the input by user typing the date-time.

**Comment by babakhani** [comment]
@torgheh 
for this purpose, you must implement your own initializer that pragmatically defines the `altField`.
