### ISSUE TITLE
عدم نمایش صحیح تاریخ

### ISSUE THREAD

**Issue by ShariatPanah** [babakhani/pwt.datepicker#167]
با سلام بنده از این دیتپیکر شما استفاده میکنم، بنده تاریخ هامو بصورت میلادی توی دیتابیس ذخیره میکنم، و سمت برنامه صرفا جهت نمایش تاریخ ها از کلاسی با عنوان PersianCulture استفاده میکنم

که بصورت خودکار میاد تاریخ های میلادی رو جهت نمایش به شمسی تبدیل میکنه حالا مشکل من با این دیتپیکر شما اینه که موقع ویرایش یک رکوردی که دارای تاریخ هستش، فیلد تاریخ که توی تکست باکس نمایش داده میشه به یه تاریخ عجیب (تو برخی موارد به سال منفی) تبدیل میشه.

دلیلشم واضحه، چون وقتی تاریخ از دیتابیس واکشی میشه بصورت میلادی هستش و اون کلاس من میاد تاریخ رو به شمسی تبدیل میکنه و توی تکست باکس قرار میده، دیتپیکر هم میاد همون تاریخ رو دوباره تبدیل میکنه و یه تاریخ دیگه بدست میاد، حالا سوال من اینه که ایا امکانش هست که من تاریخ شمسی رو بذارم توی تکست باکس بدون اینکه دیتپیکر دوباره اونرو تبدیل کنه؟

اینم نمونه:
![1](https://user-images.githubusercontent.com/32509267/31168140-3987119a-a901-11e7-9482-747e0ac46f13.png)

![2](https://user-images.githubusercontent.com/32509267/31168141-398f8eec-a901-11e7-9d13-c613454faf0c.png)

الان توی تصویر اول توی جدول، ستون تاریخ عدم حضور مربوط به دومین رکورد توی دیتابیس مقدار 2017/09/27 رو داره، همونطور که گفتم کلاسی که استفاده میکنم اون تاریخ رو صرفا جهت نمایش به شمسی تبدیل میکنه

جالب اینجاس که با هر بار رفرش صفحه ایجاد رکورد جدید و یا صفحه ویرایش، مقدار تاریخ درون تکست باکس تغییر میکنه و با سه بار رفرش، تکست باکس مربوط به تاریخ، به تاریخ امروز 
مقدار میگیره

از این کد برای دیتپیکر استفاده میکنم:
`<script type="text/javascript">
        $(document).ready(function () {
            $("#AbsentDate").persianDatepicker({
                observer: true,
                format: 'YYYY/MM/DD'
            });
        });
    </script>`
ممنون میشم در این رابطه راهنمایی کنین

**Comment by ShariatPanah** [comment]
با سلام مجدد، مشکل رو با اضافه کردن autocomplete="off" به کد جاواسکریپت حل کردم، کد به این شکل بازنویسی شد:

`<script type="text/javascript">
	$(document).ready(function () {
		$("#AbsentDate").persianDatepicker({
			observer: true,
			format: 'YYYY/MM/DD',
			autocomplete = "off"
		});
	});
</script>`

**Comment by babakhani** [comment]
@ShariatPanah 
درود این مورد در نسخه آخر برطرف شده
[Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype)
تصور من اینه که با این مثال مشکل شما حل خواهد شد
