### ISSUE TITLE
Safari Support? / عدم کارکرد با سافاری؟

### ISSUE THREAD

**Issue by Moouren** [babakhani/pwt.datepicker#170]
با سلام ، اول ازتون تشکر میکنم بابت زحماتتون ، من توی فرم استفاده کردم با کروم و فایر فاکس مشکلی نداره ولی با سافاری کلا ارور میده  داخل کنسول
ممنون میشم بگی مشکل از منه یا سافاری ساپورت نمیکنه

Hi there , first of all thanks for your time , i use this datepicker in my contact page form and it works correctly with chrome and firefox but i have issues in safari it seems the problem in some JS i check it through console 
i will be appreciate if help me to figure it out.

**Comment by babakhani** [comment]
@Moouren  Which version do you use? As I checked, everything in the final version is correct

**Comment by hsharghi** [comment]
@babakhani The only thing I've checked that is not working in Safari is initialValue with Gregorian initialValueType. Due to lack of support for new Date('some formats') function. 
I've fixed the issue, should I submit a pull request?

**Comment by babakhani** [comment]
@hsharghi please submit a pull request, Thanks.
