### ISSUE TITLE
نمایش دوباره تاریخ روز

### ISSUE THREAD

**Issue by Hamed6380** [babakhani/pwt.datepicker#171]
با سلام و تشکر
چجوری میشه وقتی ثبت اطلاعات انجام شد ، تاریخ روز رو دوباره ست کرد ...
مثلا در ثبت اطلاعات تاریخ تغییر پیدا کرده است ، بعد از ثبت اطلاعات ، تاریخ روز رو دوباره در ادیت نمایش بدهد .
ممنون

**Comment by babakhani** [comment]
@Hamed6380 
در حال حاظر چنین ویژگی ای وجود نداره. امیداوارم در نسخه های بعدی اضافه اش کنیم.
