### ISSUE TITLE
initialValue cannot parse time correctly

### ISSUE THREAD

**Issue by rziw** [babakhani/pwt.datepicker#172]
سلام
در فرم ایجاد چنانچه اینپوت دیت تایم پیکر خالی باشد بطور صحیح تاریخ و ساعت را برای انتخاب نمایش میدهد اما در فرم ویرایش که اینپوت مقدار دارد تاریخ نمایش داده برای انتخاب نیز اشتباه نمایش داده میشود (سال ۷۷5 و ماه و روز نامرتبتی برای انتخاب نمایش داده میشود)
طبق عکس در لینک زیر
https://screenshots.firefox.com/7GcvWkMbAANrrmEf/instabot.dev
آیا امکانش هست که درصورت پر بودن این اینپوت نیز تاریخ کنونی و یا همان تاریخی که پر شده نمایش داده شود؟
نحوه ی init کردن هم طبق کد زیر : 

`$('#datepicker1').pDatepicker({
        initialValue: false,
        format: 'YYYY/MM/DD HH:mm:ss',
        autocomplete :'off',
        autoClose: true,
        minDate: new persianDate().valueOf(),
        timePicker: {
            enabled: true,
            meridiem: {
                enabled: true
            }
        }
    });`

**Comment by ShariatPanah** [comment]
با سلام، منم همین مشکل رو داشتم، ولی انگار توی نسخه جدید این مورد برطرف شده. این نمونه رو نگاه بندازین
[example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype)

**Comment by rziw** [comment]
@ShariatPanah 
بله توی این مثال درست هست تا زمانی که مقدار ساعت وارد نشده باشه . ساعت و دقیقه و ثانیه که وارد بشه بهم میریزه . نهایتا فیلد تاریخ رو از ساعت جدا کردم

**Comment by samirreza** [comment]
@babakhani i have the same problem. i test many combination of input field value for showing initial date and time but i cant adjust time properly. what format should is use for this purpose ?

**Comment by samirreza** [comment]
@ShariatPanah i find solution with help of php. if you set the value attribute of field with this php method, this library can convert it to formatted value in persian :
date('D M d Y H:i:s O', $value) // $value is the timestamp of datetime field
