### ISSUE TITLE
ریلیس کردن نسخه ی یک

### ISSUE THREAD

**Issue by J-TAG** [babakhani/pwt.datepicker#173]
سلام،
ببخشید به نظرم اگه یک ریلیس برای نسخه ی ۱.۰.۰ یا بالاتر بدید خوب باشه. چون با این ریلیس هایی که الان هست، نمیشه از این افزونه در حالت 
stable 
استفاده کرد.
ممنون از شما

**Comment by babakhani** [comment]
@J-TAG ok As soon as I can.
