### ISSUE TITLE
Webpack / vue compatibility maybe?

### ISSUE THREAD

**Issue by hatrena** [babakhani/pwt.datepicker#174]
Hi, 

is there any way that i can use it on webpack or Vue? any documentation will be appreciated.

i get error ``` $.pDatepicker is not defined ``` 
- all dependencies are required in advance

Thanks

**Comment by babakhani** [comment]
@hatrena I'm trying to add this to the documentation. Thank you for your suggestion.

**Comment by babakhani** [comment]
Follow here #158
