### ISSUE TITLE
تعیین حداقل و حداکثر برای تاریخ

### ISSUE THREAD

**Issue by mromid** [babakhani/pwt.datepicker#175]
تشکر از این پلاگین 
مشکلی با این نسخه داشتم و خدمتتان اعلام میکنم

وقتی حداقل تاریخ انتخاب میکنیم به عنوان مثال امروز ( یعنی روز های قیب غیر قابل انتخاب باشد )
ولی روز های گذشته فعال و روز های آینده غیر فعال میباشند

همچنین در ماه ها نیز ماه های قبل غیر فعال و ماه های  آینده فعال میباشد و وقیتی ماه های آینده انتخاب میشود روز های آن غیر فعال است

مشکل دوم
تعیین روز های تعطیل در پلاگین به چه صورت است ؟

**Comment by babakhani** [comment]
@mromid  you must use the last version. 
there is no holiday or something like this, we have `checkDate `. you can use it to make disable every day you want.
doc: http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate
