### ISSUE TITLE
من یه دیت پیکر میخوام بسازم که فقط ماه رو بگیره

### ISSUE THREAD

**Issue by svahdati** [babakhani/pwt.datepicker#176]
سلام.من یک دیت پیکر میخوام که فقط ماه رو از کاربر بگیره.

مشکل اینجاس که باید daypicker  رو هم ترو بزارم تا اوکی بشه.
ولی من نمیخوام اینجوری بشه.فقط میخوام ماه انتخاب بشه.

دی پیکر رو اوکی کردم و کار میکنه.
کدش اینجوری شده
`$('.datepicker-day').persianDatepicker({
            viewMode: 'day',
            autoClose: true,
            format: 'DD'
        });`
ولی واسه ماه کار نمیکنه همین کد.
ماه هارو میاره.ولی انتخاب که میکنم چیزی وارد اینپوت نمیشه

```
$(؛.datepicker-month').persianDatepicker({
            viewMode: 'month',
            autoClose: true,
            dayPicker: false,
            yearPicker: false,
            format: 'MM',
            initialValue: false
        });
```

**Comment by babakhani** [comment]
@svahdati 
look at this playground, you can make your config simply
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html
