### ISSUE TITLE
انتخاب تاریخ شمسی و ذخیره بصورت کاراکترهای عددی لاتین در فیلد

### ISSUE THREAD

**Issue by silvana-tnk** [babakhani/pwt.datepicker#178]
سلام و با عرض احترام
در حال حاضر زمانی که تاریخ شمسی انتخاب می شود کاراکترهای عددی ماه و سال و روز بصورت فارسی ذخیره می گردد. در صورتی که بخواهم انتخاب تاریخ شمسی باشد و ذخیره بصورت کاراکترهای عددی لاتین در فیلد باشد چه کار باید کرد ؟

**Comment by babakhani** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#persianlocale-string

 Example
```
$('selector').persianDatepicker({
    calendar:{
         persian: {
             locale: 'en'
         }
    }
})
```

**Comment by hamed743** [comment]
سلام،
اگر بخواهیم فقط اعداد انگلیسی شوند ولی نام ماه انگلیسی نشود چکار باید کرد؟

**Comment by alihastam** [comment]
> سلام،
> اگر بخواهیم فقط اعداد انگلیسی شوند ولی نام ماه انگلیسی نشود چکار باید کرد؟

تنها راهش اینه که برید داخل فایل persian-date.min.js
دنبال همون ماه ها بگردید مثلا shahrivar رو سرچ کنید و اونها رو تبدیل کنید به فارسی 
مثلا شهریور 
برای روزها هم همینطور  sa رو تو همونجا تبدیل کنید به شنبه
