### ISSUE TITLE
هجری قمری

### ISSUE THREAD

**Issue by amirakhavan** [babakhani/pwt.datepicker#179]
سلام
با تشکر از کتابخانه بسیار عالیتون
میخواستم بدونم برنامه ای دارین که هجری قمری رو هم اضافه کنین به برنامه؟

با استفاده از سایت زیر که تقریباً تبدیلات مربوط به هجری قمری رو داره:
http://www.ar-php.org

**Comment by babakhani** [comment]
درود
در حال حاضر برنامه ای برای افزودن تاریخ قمری نداریم
شاد باشید
