### ISSUE TITLE
range selector

### ISSUE THREAD

**Issue by armanlearn** [babakhani/pwt.datepicker#180]
Hi
I want to use range selector.
every things works like charm but I want to add limitation to (to) form
I mean ((( from select time(.from) to (.from + 60days) 
think like user choose a time and only can select 10 days after time he select.

regards and tanks for your good job.

**Comment by babakhani** [comment]
@armanlearn 
I cant understand your question
i think this is helpful

http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#range-selector
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#mindate
