### ISSUE TITLE
datepicker opener button

### ISSUE THREAD

**Issue by bahmansh** [babakhani/pwt.datepicker#181]
Hi
I need a button for open datepicker. I dont wanna open datepicker by clicking on textbox space.
Will you implement this feature?

**Comment by babakhani** [comment]
you can use API method
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/

**Comment by bahmansh** [comment]
No, it's not good choice. I think better way is that you embed one opener icon in textbox, so it open datepicker instead of clicking on textbox. It can be optional:
{
    .....
    iconOpener:true,
    .....
}

**Comment by bahmansh** [comment]
I added it to your date picker but that need much effort and it affected on another parts.
If it's simple for you please add it. thanks.

@babakhani
