### ISSUE TITLE
Feature request: Css class difference between Georgian calendar and Persian calendar

### ISSUE THREAD

**Issue by sijav** [babakhani/pwt.datepicker#182]
It would be awesome to add css class onto the main element (Eg. beside datepicker-container) upon change the calendar type so we can change the style based on calendar type (Eg. chaging the font)

**Comment by babakhani** [comment]
it sounds good. In the next version will be done

**Comment by martinmikulka** [comment]
This would be also very helpful for setting proper layout for each calendar type (LTR vs. RTL).

**Comment by babakhani** [comment]
@sijav Added in v1.1.0. 
`datepicker-gregorian` and `datepicker-gregorian` toggle with calendar type, check DOM.
thanks for take time

@martinmikulka you can make your own `template` see [Document](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configtemplate-string)
