### ISSUE TITLE
Gregorian datepicker wrong date for January, and sometimes for November 

### ISSUE THREAD

**Issue by jone30rw** [babakhani/pwt.datepicker#183]
With calendarSwitch enabled, when I select a date in January the date jump to December of the same year. 
persian-datepicker version: v1.0.2
persian-date version: v1.0.1

I have inspected the view in chrome. It looks that the data-unix attribute which is generated for month's days' td elements is wrong. eg: 1 Jan 2017 => 1512110318918 which should be around 148....

The month's title is January, but the data-* is different.

![1](https://user-images.githubusercontent.com/1673598/33512640-e6292a68-d751-11e7-9d90-b620bf48c2aa.png)
![2](https://user-images.githubusercontent.com/1673598/33512665-2beebc5c-d752-11e7-96a0-b8428f556a7b.png)

**Comment by jone30rw** [comment]
@babakhani Can you please take a look at this?

**Comment by MahdiPishguy** [comment]
@jone30rw the library owner don't answer on issues, did you check samples on this link? http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/

**Comment by jone30rw** [comment]
@MahdiPishguy OK, thanks.
Yes I have checked the examples, and I have been using the library for quite a few years. 
The issue is with the new feature calendarSwitch.

I am not sure if the issue is with datepicker itself or the persian-date library.

**Comment by jone30rw** [comment]
You can also check that online examples also have the same issue. 
When you select the 1th Jan of each each the date jumps to 1th Dec of the year.
