### ISSUE TITLE
API.destroy() not working

### ISSUE THREAD

**Issue by martinmikulka** [babakhani/pwt.datepicker#187]
Hi, 

I am trying to call API method .destroy(), it seems it is not working. Please check.

HTML:

```
<div id="datepicker"></div>
<div id="destroy-btn">Destroy</div>
```

JS:
```
            $('#datepicker').persianDatepicker({
                inline: true,
                onSelect: function () {
                    console.info('onSelect callback');
                },
                onDestroy: function () {
                    console.info('onDestroy callback');
                }
            });

            $('#destroy-btn').on('click', function () {
                console.info('destroy clicked ...');
                let pd = $('#datepicker').persianDatepicker();
                pd.destroy();
            });
```

After selecting the date, new message appears in the console: "onSelect callback"
After clicking the Destroy button, only "destroy clicked ..." message appears in the console. No new message from the onDestroy callback. Datepicker remains in the DOM.

**Comment by martinmikulka** [comment]
OK, I managed to call .destroy() successfully. Instance of datepicker has to be stored in variable and the .destroy() method has to be called on the variable.

let dp = $('#datepicker').persianDatepicker({
        inline: true,
        onSelect: function () {
            console.info('onSelect callback');
        },
        onDestroy: function () {
            console.info('onDestroy callback');
        }
    });

    $('#destroy-btn').on('click', function () {
        console.info('destroy clicked ...');
        pd.destroy();
    });

It is possible to call .destroy() method multiple times. In my opinion, when .destroy() is called, everything related with that instance shoud be removed, event handlers too.

**Comment by babakhani** [comment]
@martinmikulka  In the final version, this case has been much better. remove dom elements and delete dapiecker object will be done in destroy method from v1.1.0
