### ISSUE TITLE
Mouse wheel on timepicker changes calendarType?

### ISSUE THREAD

**Issue by martinmikulka** [babakhani/pwt.datepicker#189]
Hello, 

when doing a mousewheel above the ":" in timepicker, the calendarType? changes from gregorian to persian and vice versa. It happens once, then when changing any time component, it changes back to previous type. 
Some change is also visible in the calendar part, where day numbers become filled wrong in previous and next months.

m.

**Comment by babakhani** [comment]
@martinmikulka  Fix in v1.1.0
