### ISSUE TITLE
Callback functions should provide selected date and time

### ISSUE THREAD

**Issue by martinmikulka** [babakhani/pwt.datepicker#190]
Hello, 

it would be helpful if the .onSubmit() (and maybe all other callback methods too) would provide access to selected date and time, so user would be able to use the value, ie:

```
Config = {
  toolbox: {
    submitButton: {
      onSubmit: (unix) => {
        console.info("submitted value: " + unix);
      }
    }
  } 
}
```

**Comment by babakhani** [comment]
@martinmikulka again thanks and it's a good idea

**Comment by babakhani** [comment]
@martinmikulka  I think only `onSelect` events must access to selected date and time directly.
in v1.1.0 you can access a datepicker object in all event except `onSelect` events.
you can access selected date in `state` object.


```javascript
Config = {
  toolbox: {
    submitButton: {
      onSubmit: (datepickerObject) => {
        console.info(datepickerObject);
        console.info(datepickerObject.state);
      }
    }
  } 
}
```
