### ISSUE TITLE
Time components rounding according to step

### ISSUE THREAD

**Issue by martinmikulka** [babakhani/pwt.datepicker#191]
Hello, 

traversing through time components depends on the time, when datepicker gets instantiated. For example if I make instance of picker on 11:23:12 and set timepicker.second.step = 5, then I am traversing through the seconds like 12, 17, 22, 27... 

It would be nice, if timepicker would round time parts according to the step set in the options. Using the config above I would expect to traverse through seconds like 00, 05, 10, 15, 20...

**Comment by babakhani** [comment]
@martinmikulka that sounds good. Thank you for taking the time.
