### ISSUE TITLE
با سلام

### ISSUE THREAD

**Issue by mahdimohammadi68** [babakhani/pwt.datepicker#192]
من میخوام دیتپیکرم از یک روز مشخص برام شروع بشه نه مثلا همین روز یعنی روزی انتخاب بشه که من میگم
متاسفانه نتونستم کدم رو ببنویسم اگه میشه کد مربوط به این قسمت رو بگین...

**Comment by babakhani** [comment]
@mahdimohammadi68 
درود برای اینکار لطفا لینک های زیر رو بررسی کنید
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#Config.initialValue
