### ISSUE TITLE
Different value format

### ISSUE THREAD

**Issue by EleRam** [babakhani/pwt.datepicker#193]
Is there any option to set different format for the value and using a data attribute instead of alt-field?
example: 
```
$(selector).persianDatepicker({  
	// format: 'L',  
	displayFormat: 'L', // for value attr
	valueFormat: 'X' // for data attr
});
```

**Comment by babakhani** [comment]
@EleRam 
`format` `formatter` only affect on viewable input.
`altFormat` `altFieldFormatter` affect on alt field that usually contains server friendly value.
for more info: 
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/#options-table
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#Config.altFormat

**Comment by EleRam** [comment]
I noticed that I can use `unixDate` in `formatter()` without returning anything.

thanks.
