### ISSUE TITLE
How to change font to more beautiful one

### ISSUE THREAD

**Issue by monajafi** [babakhani/pwt.datepicker#196]
I've found this date picker as most complete one to be used in jquery. Is there any convenient way to change the date picker font ?

**Comment by martinmikulka** [comment]
You can set the font in CSS.  First link this datepicker's CSS, then link your CSS, where you can apply custom styling.

**Comment by monajafi** [comment]
Thanks, I'll try

**Comment by babakhani** [comment]
follow here #198
