### ISSUE TITLE
Material design style date picker

### ISSUE THREAD

**Issue by monajafi** [babakhani/pwt.datepicker#198]
Hi 
I couldn't find any material style date picker for jalali calendar. I'm thinking to customize your date picker to looks like material date picker. please guide me what is best way to design a material style persian date picker

**Comment by babakhani** [comment]
Hi

1. [fork](https://help.github.com/articles/fork-a-repo/) project
2. run this command inside project path
`npm install` 

> install all dependencies

`npm run dev` 

> start web server on http://localhost:3000/ you can change it on this [file](https://github.com/babakhani/pwt.datepicker/blob/master/webpack.config.dev.js)

3.  add a new folder named `material` inside this [path](https://github.com/babakhani/pwt.datepicker/blob/master/src/sass/theme)
`project_root/src/sass/theme`
4. add a new file named `default.scss` to `material` folder
5. replace this line in this [file](https://github.com/babakhani/pwt.datepicker/blob/master/src/sass/persian-datepicker.scss).
path: `project_root/src/sass/persian-datepicker.scss`
`@import 'layout/default';`
with
`@import 'theme/material/default';`
6. write your material theme styles inside `sass/theme/material/default.scss` or any imported file
7. After sure everything is displayed correctly, create a pull request.

**Comment by monajafi** [comment]
Dear Mr Babakhani
I will try and report back here
Thanks

**Comment by babakhani** [comment]
@monajafi Closed because of inactivity
