### ISSUE TITLE
Value

### ISSUE THREAD

**Issue by alidehghan** [babakhani/pwt.datepicker#2]
Hello Reza,

Thanks for such an admirable work.

But there is a bug I guess. If a Persian value is set in the text-box, when you get that value by a selector, or during a serialization (such as form serialization in case of ajax posting), the value that is returned is not actual date/time value and is its Persian (Unicode) corresponded. you can find it in the following screen shot. 

I think the feature that you convert normal digits to Persian ones is very great, but I think you shouldn't change the plain value in the text-box's value (Convert to Unicode).

Great thanks again for your all efforts... :)

![image](https://f.cloud.github.com/assets/3834767/493291/d3b13cc6-bb32-11e2-9667-6c6d56e4b089.png)

**Comment by pmpr-ir** [comment]
I am at the same thing
