### ISSUE TITLE
How to change main input locale

### ISSUE THREAD

**Issue by SajjadKharrazi** [babakhani/pwt.datepicker#201]
سلام
 وقتی که تاریخ مورد نظر انتخاب بشه امکانی داشته باشه که اعداد به انگلیسی ذخیره بشن
چون برای ذخیره کردن توی دیتابیس به مشکل میخوریم و باید این اعداد فارسی رو به انگلیسی تبدیل کنیم
اینجور که من فهمیدم متودی داخل پرشین دیت دارید که همچین کاری میکنه ولی دیت پیکر نداره
locale ro ke avaz konim kolle taghivm englisi mishe vali faghat adadi ke user entekhab mikone hengame zakhire englisi beshe kafie

**Comment by pouyaSamie** [comment]
با سلام شما برای دریافت اعداد به صورت انگلیسی برای ذخیره در دیتابیس می توانید از کد زیر استفاده کنید :
 ```
 altFieldFormatter: function (unix) {
        persianDate.toLocale('en');
        return new persianDate(unix).format('YYYY/MM/DD')
    },
```

لازم به ذکر است altFieldFormatter از option های datepicker می باشد

**Comment by SajjadKharrazi** [comment]
چرا روی altField؟؟
من بخوام روی همون اینپوت اصلی این اتفاق بیفته چیکار باید کنم؟

**Comment by SajjadKharrazi** [comment]
"formatter": function (unix) {
                persianDate.toLocale('en');
                return new persianDate(unix).format('YYYY-MM-DD')
            },

حل شد
