### ISSUE TITLE
تقویم ثابت دو تاریخ جلالی و میلادی را ندارد؟

### ISSUE THREAD

**Issue by mfs0business** [babakhani/pwt.datepicker#204]
سلام
تقویم ثابت فقط فارسی دارد؟
من میخوام بتونه هردو رو داشته باشه

**Comment by babakhani** [comment]
@mfs0business 
لینک ها رو یینید
[Examples](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/)
[Playground](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html)
