### ISSUE TITLE
مناسبت ها رو چطور میتونم به تقویم اضافه کنم؟

### ISSUE THREAD

**Issue by mfs0business** [babakhani/pwt.datepicker#205]
من با این تقویم تقویم کاری درست کردم ولی چندتا مشکل دارم
1- چطور میتونم مناسبت ها و روزهای تعطیل رو مشخص کنم 
2- بعضی تاریخ ها رو که یادداشتی براش ثبت میشه رو میخوام رنگی کنم

ممنون

**Comment by babakhani** [comment]
چنین امکانی در حال حاظر وجود نداره ولی شما می تونید اونها رو به سادگی با گسترش نسخه اصلی اضافه کنید
