### ISSUE TITLE
Callback on select when is 'onlyTimePicker' (Major bug?)

### ISSUE THREAD

**Issue by ttvd94** [babakhani/pwt.datepicker#208]
I tried _onSelect_ and _onSet_ callbacks and non of them are fired when the `onlyTimePicker` is set to `true`. I assume this is a bug.

**Comment by babakhani** [comment]
@ttvd94 thank to report. yes this is bug and will be fixed at next 48 hour

**Comment by ttvd94** [comment]
Thanks for the support. Anyway, I used `formatter` callback instead and it worked fine.

**Comment by APHH890** [comment]
i have same issue when i used scroll (not up/down button click)
