### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by evazzadeh** [babakhani/pwt.datepicker#209]
چند تا مساله مهم هست که تو کار با این انتخابگر زمان مشکل ایجاد میکنه و یه سری ارتقای ساده که میتونه کار رو استانداردتر بکنه

- اولی اینکه چند روز گذشته مشاهده شد که کلا انتخابگر توی بهمن‌ماه بعد از تاریخ ۱۶ بهمن مشکل داشت و الان رفع شده و احتمالا توی محاسبات بطور کلی مشکل داشت. مشکل در تاریخ ۱۰ بهمن ۹۶ رخ داده بود.

- چرا بجای استفاده از مقدار اینپوت از یه خصیصه ساختگی استفاده میکنید؟ این باعث میشه جابجایی از حالت فعلی نیاز به تغییر داشته باشه و مشکلات دیگه‌ای رو هم توی توسعه بوجود میاره. میتونید هنگام راه‌اندازی انتخابگر زمان اون مقدار رو جابجا کنید.

- مورد سوم و مهم‌تر از همه تاریخی هست که انتخابگر تحویل میده. شاید من نتونستم توی مثال‌هاتون پیداش کنم. چطور میشه تاریخ تحویلی چه در حالت شمسی و چه در حالت میلادی یه تاریخ میلادی یا شمسی باشه؟ یعنی تحت هر شرایطی خروجی تحویلی به یه فرمت باشه.

**Comment by babakhani** [comment]
ممنون که وقت گزاشتین و پیشنهاداتتون رو نوشتین
- اگر این مورد رو دقیق تر بیان کنید شاید بتونم کمکتون کنم من موردی مشابه اون چه گفتین ندیدم

-  خیلی سخت متوجه منظورتون از این جمله می شم. به هر حال در حال حاظر توی توسعه خود تقویم مشکلی وجود نداره اگر منظورتون توسعه از بیرون هست باید مشکلتون رو دقیق تر بگین 

- [لینک](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#Config.altFieldFormatter) رو ببینید

**Comment by evazzadeh** [comment]
- برای مورد اول توی تاریخ ۱۶ بهمن کلا انتخابگر به مشکل خورده بود و بعدش هم رفع شد. احتمالا در یک بازه زمانی خاص توی محاسبات یه مشکلی دارید. چون بعدش هم رخ نداد نمیدونم چطور کمکتون کنم اون باگ رو پیدا کنید!

- مورد دوم استفاده از مقادیر پیش‌فرض اچ‌تی‌ام‌ال هست. در حال حاضر یه مقدار initialValue داریم که اون منجر به تداخل عملکرد انتخابگر تاریخ میشه. البته الان ما مشکلاتمون رو با کمی بهینه‌سازی توی زمان استفاده حل کردیم. اگر مقدار پیش فرض داشته باشیم، initialValue باید true تعریف بشه و درغیراین‌صورت، مقدارش باید false باشه تا انتخابگر درست کار کنه.


به‌طور کلی پیشنهاد میشه یه سری تنظیمات اولیه رو مطابق با وضعیت کاربردی که در عمل رخ میده تنظیم کنید. مثلا فرمت پیش‌فرض رو نمیدونم کسی اصلا از این حالت استفاده میکنه یا نه. بجای اون مقدار از فرمت عمومی تری مثل `YYYY/MM/DD` استفاده کنید.

یا مثلا این سوئیچ بین تقویم در زمان استفاده از رابط کاربری باتوجه به نوع خروجی تحویلی در عمل بلااستفاده هست که اتفاقا پیش فرض هم روشن هست که به‌نظر نمیرسه موثر باشه. برای مثال ما برای خودمون سوئیچش رو غیرفعال کردیم و تو دیزاین فارسی از تقویم شمسی و تو دیزاین انگلیسی از تقویم میلادی استفاده می‌کنیم.

از طرفی امکان استفاده از خصیصه‌های داده‌ای اچ‌تی‌ام‌ال `data-*` هم میتونه این انتخابگر رو تقویت کنه تا بتونه موثرتر عمل کنه.

در نهایت ممنون از تلاش‌هاتون برای توسعه یکی از مشکلات طراحان وب ایرانی;)
