### ISSUE TITLE
onload or oninitialized event ?

### ISSUE THREAD

**Issue by ho3ein-mola** [babakhani/pwt.datepicker#211]
first thank's :+1:  for this great project !
secend : is there any other event  than onSelect() ? like onLoad or onInitialized(), i want to disable specific day onload wit jquery. like this.
```java script
onInitialized: function(
    $('tr').find("td[data-unix="+unix+"]").addClass('disabled');
}
```

so it will disable that day i got from MYSQL database by Unix timestamp ;
i tried to access $(this) but it's references to whole DATAPICKER object.

**Comment by ho3ein-mola** [comment]
actually i search for way to disable specific day that i got from database;

**Comment by babakhani** [comment]
@ho3ein-mola thanks alot.
for this purpose you can use `checkDate` option
look at [document](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configcheckdate-function)
example [example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate)

**Comment by ho3ein-mola** [comment]
but checkdate disable that day for all week .I try to disable day to just specific day . like 96/3/11
is it possible ? 
or any help to extend this project . thank's for answer .

**Comment by babakhani** [comment]
> but checkdate disable that day for all week 

this is behaviur of my example, look at example code carefully and you will find it

i write and example for you case
```javascript
$('.check-date-example').persianDatepicker({
    checkDate: function(unix){
        var disableDate = new persianDate([1396, 3, 11]);
        if( new persianDate(unix).isSameDay(disableDate)) {
            return false
        } else {
            return true
        }
    }
});
```

**Comment by ho3ein-mola** [comment]
work like charm !.thank's .
