### ISSUE TITLE
محدود کردن انتخاب تاریخ فقط به ماه جاری

### ISSUE THREAD

**Issue by ShariatPanah** [babakhani/pwt.datepicker#212]
سلام، چطوری میتونم امکان انتخاب تاریخ رو فقط به ماه جاری محدود کنم، یعنی مثلا فقط از امروز(برای مثال بیست و دوم) تا 30 یا 31 ماهی که در حال حاضر در اون قرار داریم قابل انتخاب باشه، ممنون میشم کدی واسه این بهم بدین

**Comment by babakhani** [comment]
[Live Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html)
you can use `minDate` and `maxDate` options for this purpose.

**Comment by ShariatPanah** [comment]
ممنون بابت پاسختون، بله میدونم باید از این دو پراپرتی استفاده کنم، منتها نحوه محاسبه
maxDate 
رو نمیدونم به چه شکل انجام بدم که دقیقا تا اخر ماه باشه

**Comment by abbasgholia** [comment]
با سلام
چطور میتونم فقط ماه و سال رو در پنجره تقویم نشون بده و دیگه روز رو نشون نده؟
خروجیم 139705 هست برای فیش حقوق و نیاز به ماه و سال است
