### ISSUE TITLE
set datepicker default input value empty

### ISSUE THREAD

**Issue by MisaghMi** [babakhani/pwt.datepicker#213]
Hi, thanks for this beautiful and powerful datepicker
1- how can I set default value of datepicker ,as it initialize, empty ?
2- I have a problem, when I set minDate or maxDate value, it just sets for jalali dates not for Georgian.
3- I think it's a good idea if you add CDN for  datepicker and persiandate because every time these could be updated automatically.
Thanks again

**Comment by babakhani** [comment]
1. See [document](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configinitialvalue-boolean)
2. See [playground](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html), I think there is an an issue in your implementation.
if you can provide more example of your code i can help more.
3. it sounds good, also will be added to document.


## CDN

- persian-date.js [uncompressed](https://unpkg.com/persian-date@latest/dist/persian-date.js) | [minified](https://unpkg.com/persian-date@latest/dist/persian-date.min.js)
- persian-datepicker.js [uncompressed](https://unpkg.com/persian-datepicker@latest/dist/js/persian-datepicker.js) | [minified](https://unpkg.com/persian-datepicker@latest/dist/js/persian-datepicker.min.js)
- persian-datepicker.css [uncompressed](https://unpkg.com/persian-datepicker@latest/dist/css/persian-datepicker.css) | [minified](https://unpkg.com/persian-datepicker@latest/dist/css/persian-datepicker.min.css)
