### ISSUE TITLE
مشکل در استفاده از API

### ISSUE THREAD

**Issue by abotalebie** [babakhani/pwt.datepicker#215]
با سلام و تشکر بابت این تقویم خوب

من در استفاده از ای پی آی ها مشکل دارم
طبق مستندات برای استفاده از ای پی آی ها باید ابتدا با استفاده از کد زیر تقویم را انتخاب کنیم

`var pd = $('.selector').persianDatepicker();`

اما وقتی این کد اجرا میشه کل تنظیمات تقویم از بین میره و تنظیمات پیش فرض اعمال میشه. لطفاً راهنمایی کنید که چطور باید از ای پی آی ها استفاده کنم.

[نمونه کد](https://jsfiddle.net/bsj5k262)

با تشکر

**Comment by babakhani** [comment]
[Document](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/)
