### ISSUE TITLE
مرتب سازی دیالوگ و کنترل اصلی از سمت راست

### ISSUE THREAD

**Issue by nasserman** [babakhani/pwt.datepicker#217]
برای اینکه وقتی روی کنترل کلیک می شه و دیالوگ انتخاب تاریخ نمایش داده می شه، گوشه سمت راست دیالوگ و گوشه سمت راست کنترل اینپوت با هم یکی باشند این کد رو تغییر دادم 

تابع setPickerBoxPosition از فایل persian-datepicker.js

`value: function setPickerBoxPosition() {
            var inputPosition = this.model.input.getInputPosition(),
                inputSize = this.model.input.getInputSize();

            if (Helper.isMobile && this.model.options.responsive) {
                return false;
            }

            if (this.model.options.position === 'auto') {
                this.$container.css({
                   >>> right: ($(window).width() - inputPosition.left-inputSize.width+200) + 'px',
                    top: inputSize.height + inputPosition.top + 'px'
                });
            } else {
                this.$container.css({
                    // left: this.model.options.position[1] + inputPosition.left + 'px',
                  >>>  right: ($(window).width()-this.model.options.position[1]-inputPosition.left+200) + 'px',
                    top: this.model.options.position[0] + inputPosition.top + 'px'
                });
            }
        }`

در حالت زبان های چپ به راست هر دو از گوشه سمت چپ باید ست بشن ولی در زبان راست به چپ باید از گوشه های سمت راست استفاده بشه
لطفا این تغییر رو بررسی بفرمایید و اگر ایراد نداشت به کد اصلی اضافه کنید
ممنون

**Comment by babakhani** [comment]
درود
این موضوع رو در لینک زیر پیگیری می کنیم
https://github.com/babakhani/pwt.datepicker/pull/218
