### ISSUE TITLE
امکان فعال غیر فعال و دادن استایل به روز ها

### ISSUE THREAD

**Issue by erfanpp** [babakhani/pwt.datepicker#219]
سلام
من میخوام یه سری روز ها رو روی تقویم غیر فعال کنم و به بعضی ها رو یه تگ بج اضافه کنم چطوری ممکنه؟

**Comment by babakhani** [comment]
@erfanpp 
لطفا لینک زیر را ببینید
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate

در رابطه با استایل دادن
در حال حاضر برای این کار گزینه ای وجود نداره شما باید از طریق رویداد  ها اون رو پیاده سازی کنید
