### ISSUE TITLE
btn-prev event

### ISSUE THREAD

**Issue by anooshpm87** [babakhani/pwt.datepicker#222]
how could I respond to the onShow and btn-prev event with my own function?

**Comment by babakhani** [comment]
@anooshpm87 
please read the document and if your problem doesn't solve add more description to your issue
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#onshow
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#onprev
