### ISSUE TITLE
Append to body problem in bootstrap modal

### ISSUE THREAD

**Issue by alirezasaffari** [babakhani/pwt.datepicker#228]
hi, i have used picker in bootstrap modal but every time i open and close modal it append date picker to body, so page height increased as mentioned in scroll bar, as i see in inspector date picker value added after footer of page as shown in screenshots. what is the problem??

![screenshot 11](https://user-images.githubusercontent.com/26344889/40100370-ed27e786-58f8-11e8-9e85-31554062e36b.png)
![screenshot 12](https://user-images.githubusercontent.com/26344889/40100375-f0e29600-58f8-11e8-9eb7-9a0ee2c34b81.png)
![screenshot 13](https://user-images.githubusercontent.com/26344889/40100382-f4bfd04e-58f8-11e8-9a3f-d4a8c3319b06.png)
![screenshot 14](https://user-images.githubusercontent.com/26344889/40100388-f7bf1e62-58f8-11e8-8f1e-ff47b4b57a47.png)

**Comment by alirezasaffari** [comment]
i have already fix this by removing div created by class name on modal closing. but i think it should be a datepicker issue to handle this. my code in javascript in as below

$('#modalbox').on('hidden.bs.modal', function () {
            $('.datepicker-container').remove();
        });

**Comment by babakhani** [comment]
@alirezasaffari  
I can't reproduce your issue.
could you create an example on http://jsfiddle.net?
if the problem still exists and you can create an example please reopen this issue. 
Sorry for late
