### ISSUE TITLE
Disabled and Selected days issue

### ISSUE THREAD

**Issue by kodfire** [babakhani/pwt.datepicker#230]
Hi there :)

I have fetched the dates should be disabled/selected and I do it just by finding data-date attribute and set the class disabled/selected to it However when I click on each previous month, next month, today and any other button, it removes them all. How can I prevent this not to remove those disabled/selected days when I click on each button?! Thanks

**Comment by babakhani** [comment]
@kodfire Unfortunately, at the moment, there is no way to set selected days or situation like this.
