### ISSUE TITLE
انتخاب خودکار اولین تاریخ فعال

### ISSUE THREAD

**Issue by aliworkshop** [babakhani/pwt.datepicker#235]
سلام آقای باباخانی
ضمن عرض ارادت و خسته نباشید
میخواستم کاری کنم ک اولین تاریخ غیر تعطیل و فعال به طور خودکار انتخاب و فعال بشه  ولی در حال حاضر این امکان رو نتونستم پیاده کنم

میشه کمکم کنید واسه این مورد ؟
ممنون و تشکر

**Comment by babakhani** [comment]
درود متاسفانه در حال حاضر چنین امکانی وجود نداره و شما باید با چند خط کد این کار و انجام بدین
احتمالا لینک زیر رو هم دیدن
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/#API+setDate
