### ISSUE TITLE
set default time in inline view

### ISSUE THREAD

**Issue by roozgar** [babakhani/pwt.datepicker#236]
hello
i tried to set this like

`pd.data({date: '1390-07-05'});`
or with `update `and `setdate`
but all of these not working
is there any way to set time in this date picker programmatically !?
thank you

**Comment by babakhani** [comment]
@roozgar 
Please check document
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/#apisetdateunix

**Comment by roozgar** [comment]
thank you
this is a good job :)

i used the inline method for resolve my problem after a while
like this
data-date='5/25/2018'

i used your product here:
https://bazmineh.com/calendar/
for this i used a lot of custom tricks
i hope you add some extra api methods and some custom css classes to each day to a better customization..
