### ISSUE TITLE
مشکل در ست کردن زمان پیشفرض بصورت یونیکس

### ISSUE THREAD

**Issue by webafra** [babakhani/pwt.datepicker#238]
سلام جناب باباخانی ،‌وقت بخیر .

تشکر بابت پکیج خیلی خوب و مفیدتون .
متاسفانه مشکلی دیدم که گفتم شاید نیاز به گزارش باشه 

۱ - زمانی که مقداری بصورت یونیکس به متد داده میشه ، ساعت و دقیقه و همچنین ثانیه رو لحاظ نمیکنه و ست نمیشه
۲ - در رویداد onSelect ، زمانی که ساعت و دقیقه تغییر میکنه ، مقدار آگومان ورودی متد مقداری نداره و آندیفایند میده 
یعنی انگار تغییری صورت نگرفته .
۳ - زمانی که یک مقدار برای ساعت انتخاب شد ( یعنی وقتی ساعت تغییر میکنه ) و بعد از اون تاریخ رو تغییر میدیم ،  تغییر تاریخ لحاظ میشه اما ساعت خیر !
حتی با فشردن دکمه امروز هم رویدادی که بالا نوشتم ، فراخوانی نمیشه .

نحوه استفاده بنده به اینصورته : 

```
let myDatepicker = locale === 'en' ? miladi : jalali;
                myDatepicker.onSelect = (unix) =>{
                    console.log('datepicker select : ' + unix);
                };



$(document).ready(function() {
                    $(".datepicker").pDatepicker(
                        myDatepicker
                    ).setDate(value);
                });

```

ممنون میشم راهنمایی بفرمایید .
متشکرم .

**Comment by pigivc** [comment]
سلام اگه ممکنه راهنمایی فرمایید چطوری می تونم ساعت تاریخ رو به یه ساعت دلخواه تنظیم کنم.
اگه نمونه کد هم باشه ممنون میشم.
