### ISSUE TITLE
اعداد لاتین

### ISSUE THREAD

**Issue by hamed743** [babakhani/pwt.datepicker#241]
با سلام،
من می خواهم که لوکال تقویم فارسی باشد ولی اعداد اینپوت به صورت لاتین نمایش داده شود.
آیا امکان پذیر است؟

**Comment by sdaliri** [comment]
سلام    
  
https://stackoverflow.com/questions/31439604/how-to-convert-persian-and-arabic-numbers-inside-a-string-to-english-using-javas  
  
ببین این کارت رو راه میندازه من از این استفاده کردم

**Comment by babakhani** [comment]
@hamed743 
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#persianlocale-string
test it in calendar tab inside the playground
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html
