### ISSUE TITLE
Probelm with IE with Symbol.iterator

### ISSUE THREAD

**Issue by mahyar-dodo2** [babakhani/pwt.datepicker#246]
Hi everyone ! 
I have simple and also at the moment very hard problem with this datepicker in IE 11,
I want to use datepicker in IE browser but when I load picker in a new page I have an error in Developers console like this : 

`SCRIPT5009: 'Symbol' is undefined`
`persian-datepicker.js (3199,25)`

the error refers to usage of Symbol that I think it is part of es6 in line of 3199 and column of 25 in source code of datepicker. 
I have tried some pollyfill scripts around the net to overcome the problem but they didn't work properly and some of them need some sort of dependencies that really I can not search and find them manually, 
I wanted to know is there any simpler way to use this awesome datepicker in IE or I should select another datepicker for my IE version of web application ? 
Thanks in advance 
و بسیار متشکرم !

**Comment by hassanAdamineJad** [comment]
Hi 
I had this problem too and added this script to fix it

`<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=default%2CArray.prototype.%40%40iterator%2CArray.prototype.entries%2CArray.prototype.values%2CSymbol%2CSymbol.hasInstance%2CSymbol.isConcatSpreadable%2CSymbol.iterator%2CSymbol.match%2CSymbol.replace%2CSymbol.search%2CSymbol.species%2CSymbol.split%2CSymbol.toPrimitive%2CSymbol.toStringTag%2CSymbol.unscopables%2CObject.keys%2CArray.prototype.keys"></script>`
