### ISSUE TITLE
Upgrade to jQuery 3

### ISSUE THREAD

**Issue by jasverix** [babakhani/pwt.datepicker#247]
I think your package already works with jQuery 3 - but the package.json requires jQuery 2. Maybe it is just to increase version number there.

Output from npm audit
```
> npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  High            Cross-Site Scripting (XSS)

  Package         jquery

  Patched in      >=3.0.0

  Dependency of   persian-datepicker

  Path            persian-datepicker > jquery

  More info       https://nodesecurity.io/advisories/328

found 1 high severity vulnerability
```

**Comment by evazzadeh** [comment]
No it not work with jquey3
need some change like

1. change all `.bind(` to `.on(`
2. change all `.unbind(` to `.off(`
3. remove shorthand method call. change `.keydown(function` to `.on("keydown", function` 

https://stackoverflow.com/questions/38276594/upgrade-jquery-to-3-0-rewrite-bind-to-on-unbind-to-off
