### ISSUE TITLE
Plain English numbers

### ISSUE THREAD

**Issue by loolooyyyy** [babakhani/pwt.datepicker#249]
Hi, after reading https://github.com/babakhani/pwt.datepicker/issues/141 apparently it's not possible to have Persian localization, but English digits? The `persianDigit` flag doesn't seem to work.

Can I get this formatting: `2 شهریور 1397`
And not: `۲ شهریور ۱۳۹۷`

Cheers!

**Comment by babakhani** [comment]
@loolooyyyy to do this you need reading this documents
http://babakhani.github.io/PersianWebToolkit/doc/persian-date/#tolocale
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configformatterunixdate
if you need more help please reopen this issue. good luck.

**Comment by masoodvahid** [comment]
سلام
ببخشید من در استفاده از این کتابخانه تازه کار هستم . متاسفانه متوجه نشدم که چطور باید در تنظیمات کاری کنم که تمامی تقویم فارسی بماند و فقط اعداد در اینپوت به لاتین تغییر کنند. 
اعداد فارسی در اعتبار سنجی فرم ها ایجاد اشکال می کنند.

تشکر از لطف شما

**Comment by AmirRezaM75** [comment]
@masoodvahid 
I use this approach
```js
formatter: function(unix) {
    var date = new persianDate(unix);
    var gregorian = date.toLocale('en').toCalendar('persian');
    return gregorian.format("YYYY-MM-DD");
}
```
