### ISSUE TITLE
مقدار داشتن selected قبل از انتخاب تاریخ توسط کاربر

### ISSUE THREAD

**Issue by m-alikhani** [babakhani/pwt.datepicker#251]
سلام
زمانی که کاربر هنوز تاریخی را انتخاب نکرده و مقدار initialValue هم false گذاشتیم، در state.selected دارای مقدار (تاریخ روز) است. چطور می شود متوجه شد کاربر تاریخی را انتخاب کرده یا نه؟
و همچنین تاریخ در فرم ما اجباری نیست، می خواییم با یک دکمه بتونه تاریخی که انتخاب کرده رو حذف کنه. 
ممنون میشم راهنمایی کنید.

**Comment by zolipon** [comment]
سلام
من هم این مسئله رو دارم. میخوام یه تاریخ پیش فرض (مثلا 30 روز پیش) در زمان لود صفحه وجود داشته باشه و این مقدار بعنوان تاریخ نمایشی در تقویم هم باشه.
اینطوری تاریخ رو نمایش میدم ولی توی تقویم انتخاب نشده:
document.getElementById('InpStartDate').setAttribute('value', moment(new Date()).subtract(30, 'd').format('jYYYY/jMM/jDD'));

**Comment by zolipon** [comment]
First:
document.getElementById('InpStartDate').setAttribute('value', moment(new Date()).subtract(30, 'd').format('jYYYY/jMM/jDD'));

Then:
$('#InpStartDate').persianDatepicker({
                altFormat: 'YYYY/MM/DD',
                altField: '#InpStartDate',
                initialValueType: 'persian',
                initialValue: false,
            });

**Comment by zolipon** [comment]
> 
> 
> سلام
> زمانی که کاربر هنوز تاریخی را انتخاب نکرده و مقدار initialValue هم false گذاشتیم، در state.selected دارای مقدار (تاریخ روز) است. چطور می شود متوجه شد کاربر تاریخی را انتخاب کرده یا نه؟
> و همچنین تاریخ در فرم ما اجباری نیست، می خواییم با یک دکمه بتونه تاریخی که انتخاب کرده رو حذف کنه.
> ممنون میشم راهنمایی کنید.

First:
`document.getElementById('InpStartDate').setAttribute('value', moment(new Date()).subtract(30, 'd').format('jYYYY/jMM/jDD'));`

Then:
`$('#InpStartDate').persianDatepicker({
                altFormat: 'YYYY/MM/DD',
                altField: '#InpStartDate',
                initialValueType: 'persian',
                initialValue: false,
            });`
