### ISSUE TITLE
امکان انتخاب چند تاریخ 

### ISSUE THREAD

**Issue by Ali-Azmoud** [babakhani/pwt.datepicker#257]
درود
بابت این دیت پیکر کاربردیتان ممنون

لطفا اگر امکان دارد قابلیت انتخاب چند تاریخ به صورت همزمان را اضافه نمایید
[مثل این لینک](https://alloyui.com/examples/datepicker/multiple)

سپاس

**Comment by babakhani** [comment]
@Ali-Azmoud #157 #180

**Comment by SamaeeGhader** [comment]
با سلام ... کتابخانه خوبی هست توی بعضی از پروژه هام استفاده کردم
انشاا... موفق باشید
امکانی که گفته شد رو در تقویم اعمال کنید خیلی کاربردی و عالی میشه 
امکان انتخاب چند تاریخ بصورت همزمان
