### ISSUE TITLE
Off-Canvas

### ISSUE THREAD

**Issue by hhkoosha** [babakhani/pwt.datepicker#260]
Hi,

The direction the picker is shown must change accordingly, based on canvas. As you can see, half the picker is off the screen.

I tried to fix it using css, but it's clunky and doesn't work well. Also I tried to use javascript, but my javascript sucks, so on small screens, the picker jumps from left, to right, to left, to right, ...

could you please kindly fix it?
many thanks.

![screenshot from 2018-10-26 08-40-59](https://user-images.githubusercontent.com/3070413/47681407-a313b300-dbde-11e8-8a27-788f994e7aa6.png)
![screenshot from 2018-10-26 08-41-47](https://user-images.githubusercontent.com/3070413/47681409-a444e000-dbde-11e8-8792-1dadb63243b2.png)

**Comment by pmpr-ir** [comment]
Same problem here. Any solutions?

**Comment by Farshadi73** [comment]
I have same problem, :(
