### ISSUE TITLE
Problem with syntax

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [babakhani/pwt.datepicker#263]
While using with Odoo11(odoo.com ) and python3, 
https://www.odoo.com/apps/modules/11.0/web_hijri_date/:

The problem comes as the syntax is wrong on MonthGrid and TEMPLATE for 'use strict'.
It did not allow us to use the module further.
Our fix is in the PR linked to this issue.

**Comment by babakhani** [comment]
#264
