### ISSUE TITLE
انتخاب تاریخ با یک تقویم و دریافت مقدار با تقویم دیگر

### ISSUE THREAD

**Issue by mokhosh** [babakhani/pwt.datepicker#268]
ببخشید این امکان داره که کاربر با تقویم شمسی تاریخ رو انتخاب کنه اما مقداری که ما میگیریم به میلادی باشه؟

**Comment by babakhani** [comment]
@mokhosh 
Please read the documents
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configaltfield-boolean
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#altfield
