### ISSUE TITLE
Persian digit just in value

### ISSUE THREAD

**Issue by bahmansh** [babakhani/pwt.datepicker#270]
I need calendar view digits be persian but when i select day value be english digit.
How should i do it?

![ashampoo_snap_ 5 1397_11h19m06s_001_](https://user-images.githubusercontent.com/19801131/49000720-ba0edc00-f16f-11e8-907a-7cfa52472bfa.png)

**Comment by babakhani** [comment]
@bahmansh 
Please read the documents
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configaltfield-boolean
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#altfield
