### ISSUE TITLE
datepicker view in modal

### ISSUE THREAD

**Issue by bahmansh** [babakhani/pwt.datepicker#271]
when i use it in modal, because of adding it to body, when i scroll picker scroll too.

**Comment by babakhani** [comment]
@bahmansh 
look at this [Examples](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/)
I think it's not related to pwt.datepicker if you think its an issue with pwt.datepicker, open issue and create an example on http://jsfiddle.net.
