### ISSUE TITLE
problem in selectin first day of Esfand month for every year.

### ISSUE THREAD

**Issue by gharabaghi** [babakhani/pwt.datepicker#279]
hello.
i have a big problem with this library. when i click on first day of esfand (in every year) it jumps to first day of farvardin.
does anyone else has this  problem?

**Comment by babakhani** [comment]
@gharabaghi 
could you please give us more details around your issue?
i cant see this problem in playground.
please check [here](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html)

**Comment by gharabaghi** [comment]
the strange problem is gone! surprising and confusing! yesterday at 30th Bahman problem occured. for current year and next years. we could not select 1st day of Esfand. for now it's seemingly solved!

**Comment by gharabaghi** [comment]
i  understood something strange! this problem happens in last day of Bahman!
