### ISSUE TITLE
98 جا افتادن دوم فروردین

### ISSUE THREAD

**Issue by javansolo** [babakhani/pwt.datepicker#280]
با سلام  و خسته نباشید
دوم فروردین 98 در نمایش اسفند 97 جامانده است
تصویر گویای این مطلب است
![untitled](https://user-images.githubusercontent.com/11363999/53299336-b9104800-384d-11e9-9f98-0fc01c2cc37f.png)

**Comment by babakhani** [comment]
@javansolo thanks for report

**Comment by imani013** [comment]
سلام وقتی تاریخ قبل سال 1354 انتخاب می کنیم ، هنگام ست کردن تاریخ هنگام ویرایش به عنوان مثال 1354/05/25 تاریخ ثبت شده بود اما زمان ست کردن 1354/05/24 انتخاب میشه
 if (data_model.BirthDate !== null && data_model.BirthDate !== '') {
          
            var pd = $('#Mod_BirthJalaliDate').pDatepicker({
                observer: true,
                format: 'YYYY/MM/DD',
                "autoClose": true,
                "altField": '#Mod_altBirthJalaliDate',
            })
            pd.setDate(parseInt(data_model.BirthDate.substr(6)));
            $('#Mod_BirthJalaliDate').val(data_model.JalaliBirthDate);
        } else {
            $('#Mod_BirthJalaliDate').pDatepicker({
                observer: true,
                format: 'YYYY/MM/DD',
                "autoClose": true,
                "altField": '#Mod_altBirthJalaliDate',
                initialValue: false,
            });
        }
