### ISSUE TITLE
Show equivalent date in another input

### ISSUE THREAD

**Issue by Ahmadrameen** [babakhani/pwt.datepicker#281]
After selecting Solar date (first input - .solarDate) show the equivalent Gregorian date in (second input -  .gregorianDate).

```
<input class='solarDate'>
<input class='gregorianDate' hidden>
```

**Comment by mehrankordavani** [comment]
i need this answer too. could you find the solution? @Ahmadrameen

**Comment by mort3za** [comment]
If I understood your problem correctly, you can use `onSelect` callback and convert the selected date manually by persianDate package and use it everywhere you need (e.g. set the value of a second input).

**Comment by mehrankordavani** [comment]
@mort3za thanks it was the answer.


@Ahmadrameen i did what @mort3za  said like below:
```
onSelect: function(unix){
          var $datenew= new persianDate(unix).toLocale('en').toCalendar('gregorian').format('l');
          $('#inputGroupAlt3').val($datenew);
    },
```

my input field with id inputGroupAlt3 will get equivalent Gregorian date after every date selection by user.
