### ISSUE TITLE
بدست اوردن ماه و سال جاری

### ISSUE THREAD

**Issue by amin3d** [babakhani/pwt.datepicker#282]
سلام، می خواستم بدونم  آیا روی onNext و onPrev می شه مقدار ماه و سال جاری را بدست اورد، من روی تقویم اینطور می خواهم داشته باشم که کاربر وقتی بین ماهها navigate می کنه یک درخواست به سرور ارسال می شه و فرضا روزهایی که کاربر پیش از این انتخابی کرده روی تقویم به نمایش در می ایند، الان توی doc چیزی پیدا نکردم

**Comment by babakhani** [comment]
متاسفانه متوجه منظورتون نمی شم. اگر مایل بودید این مورد رو دوباره باز کنید و با درج توضیحات بیشتر یا حتی یه نمونه کد در لینک زیر
http://jsfiddle.net
