### ISSUE TITLE
بستن پیشفرض تقویم چند انتخابی

### ISSUE THREAD

**Issue by esmaeilvahedi** [babakhani/pwt.datepicker#286]
با سلام و تشکر از رحمات شما
چطور میتونم در انتخاب تاریخ چند انتخابی تقویم پیش فرض بسته باشد وقتی در المنت مربوطه کلیک شد تقویم باز وپس از آن بسته شود
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#range-selector

**Comment by babakhani** [comment]
Hi,
Check inline config in [Document](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configinline-boolean)
