### ISSUE TITLE
مشکل در انتخاب تاریخ مهر 1223

### ISSUE THREAD

**Issue by alikhazeni** [babakhani/pwt.datepicker#289]
سلام 
مشکلی که  داشتم در تاریخ 1398/1/31 کاربر میخواست تاریخ 1223/7/2 رو انتخاب کنه ولی دیت پیکر تاریخ 1223/8/2 رو انتخاب میکرد 
چطوری میتونم این مشکل رو حل کنم  ؟ 
با تشکر

**Comment by babakhani** [comment]
درود
این مشکل بر طرف شده و در نسخه بعد در اختیار شما خواهد بود
شاد باشید

**Comment by alikhazeni** [comment]
تشکر از شما نسخه بعدی انشالله کی منتشر میشه؟

**Comment by babakhani** [comment]
در تلاشم توی چند روز آینده نسخه جدید رو منتشر کنم. اگر مایل هستین کمکی کنید آدرس نسخه جدید رو براتون می فرستم تا بتونید قبل از انتشار تست کنید

**Comment by alikhazeni** [comment]
مهندس بفرستین  تست میکنم موردی براتون میگم حل کنید 
تشکر از شما

**Comment by babakhani** [comment]
@alikhazeni 
you can test the new rc version.
`npm install persian-date@next`
`npm install persian-datepicker@next`
