### ISSUE TITLE
مشکل در minDate و maxDate

### ISSUE THREAD

**Issue by javadx** [babakhani/pwt.datepicker#29]
سلام
تو آخرین ورژنی که گذاشتید
من یه minDate ست کردم و مقدارش ماه آبان سال 1388 هست
تو سال 88 فقط ماه آبان فعال میشه و بعد از اون غیر فعاله مقدار timestamp هم مقدار زیره

1258675200000
موفق باشید

**Comment by babakhani** [comment]
Thanks for your report. i'll fix it as soon as possible.
