### ISSUE TITLE
آپدیت نشدن تکس باکس 

### ISSUE THREAD

**Issue by nimamsv** [babakhani/pwt.datepicker#291]
درسته متن خوانا نیست اما فکر میکنم مشکل من هم همینه
زمانیکه با پیکر تکس باکس آپدیت میشه تاریخ روی فیلد ثبت میشه اما سمت سرور چیزی ارسال نمیشه من فکر میکنم دی او ام آپدیت نمیشه . زمانی دیتا ثبت میشه که بعد از انتخاب دیت با پیکر اینتر زده بشه یا روی خود تکس باکس مجددا کلیک کنید و چیزی رو دستی تغییر بدین.
اگه ممکنه راهنمایی بفرمایید

_Originally posted by @nimamsv in https://github.com/babakhani/pwt.datepicker/issues/113#issuecomment-491191206_

**Comment by aliarsh** [comment]
باید name تگ input را تنظیم کنید و سمت سرور دریافتش کنید.
set name of tag input for get server side data
