### ISSUE TITLE
wrong date with `setDate` and `persianDate` functions

### ISSUE THREAD

**Issue by mohsen12999** [babakhani/pwt.datepicker#293]
```js
var $cl = $('#date-from').persianDatepicker();
$cl.setDate(new persianDate().unix()); //دوشنبه, ۲۹ دی ۱۳۴۸
```

**Comment by hatamiarash7** [comment]
با استفاده از مثالی که تو صفحه آموزش خود کتابخانه هست ، کمی اعداد و ارقام رو جابجا و مقایسه کردم.

مقداری که کتابخانه صحیح نشون بده با این فرمول به دست میاد :

```js
setDate(unix * 1000 + 48891100)
```

**Comment by armin-git** [comment]
> با استفاده از مثالی که تو صفحه آموزش خود کتابخانه هست ، کمی اعداد و ارقام رو جابجا و مقایسه کردم.
> 
> مقداری که کتابخانه صحیح نشون بده با این فرمول به دست میاد :
> 
> ```js
> setDate(unix * 1000 + 48891100)
> ```

میدونم خیلی دیر جواب میدم ولی جواب شما اشتباهه. نباید یک مقدار به یونیکس اضافه کرد. باید با لایبرری moment تاریختوت رو به ابچکت مامنت تبدیل کنید بعدش با لایبرری مامنت جلالی اون رو به فارسی تبدیل کنید و در نهایت تاریخ فارسی رو بگیرید.
```
var d=moment.utc(moment(date).format('DD/MM/YYYY HH:mm:ss'), 'DD/MM/YYYY HH:mm:ss');
var dateej = d.locale('fa');
```
برای گرفتن تاریخ فارسی هم در انتها فرمت زیر رو انجام بدید
`dateej.format('DD/MM/YYYY HH:mm:ss')`

دلیل اینکه از این لایبرری ها استفاده میکنیم اینکه اشتباهیی در تبدیلات بووجود نیاد.
