### ISSUE TITLE
ست کردن تاریخ اشتباه قبل از سال عای 1354

### ISSUE THREAD

**Issue by imani013** [babakhani/pwt.datepicker#294]
سلام وقتی تاریخ قبل سال 1354 انتخاب می کنیم ، هنگام ست کردن تاریخ هنگام ویرایش به عنوان مثال 1354/05/25 تاریخ ثبت شده بود اما زمان ست کردن 1354/05/24 انتخاب میشه

 if (data_model.BirthDate !== null && data_model.BirthDate !== '') {
          
            var pd = $('#Mod_BirthJalaliDate').pDatepicker({
                observer: true,
                format: 'YYYY/MM/DD',
                "autoClose": true,
                "altField": '#Mod_altBirthJalaliDate',
            })
            pd.setDate(parseInt(data_model.BirthDate.substr(6)));
            $('#Mod_BirthJalaliDate').val(data_model.JalaliBirthDate);
        } else {
            $('#Mod_BirthJalaliDate').pDatepicker({
                observer: true,
                format: 'YYYY/MM/DD',
                "autoClose": true,
                "altField": '#Mod_altBirthJalaliDate',
                initialValue: false,
            });
        }

**Comment by mort3za** [comment]
I don't think so. Please check this example: https://codepen.io/mort3za/pen/bGBrBKP
