### ISSUE TITLE
How to disable Gregorian from calendar?

### ISSUE THREAD

**Issue by mrmmg** [babakhani/pwt.datepicker#299]
Hi
I want to disable Gregorian type from my calendar. **I use this option but it's not working**:
`calendar: {
    gregorian: {
                    enabled: false
                }
}`

#### also, see this image
![Annotation 2019-07-16 085750](https://user-images.githubusercontent.com/30490118/61266376-d74cf500-a7a8-11e9-9bc1-2c4c46c3e590.jpg)

**please explain to me.**

**Comment by babakhani** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#toolboxcalendarswitch-object
