### ISSUE TITLE
ماسک نشدن ویرایشگر

### ISSUE THREAD

**Issue by ghbn1362** [babakhani/pwt.datepicker#302]
ویرایشگر الان امکان ورود هر نوع داده ای رو میده و می توان داخلش متن هم نوشت بهتر این حالت بر اساس فرمت کنترل بشه و فقط کارکترهای مجاز قابل ورود باشه بر اساس ساختار فرمت مشحص شده این طوری ولید بودن و استفاده از پلاگین خیلی راخت تر میشه

**Comment by babakhani** [comment]
@ghbn1362 it's a good feature, i consider it in next version, thanks
