### ISSUE TITLE
تکرار روز اول ماه

### ISSUE THREAD

**Issue by esfahanweb** [babakhani/pwt.datepicker#305]
<div dir="rtl">
ضمن عرض سلام و تشکر بابت پکیج بسیار خوبتون

یه مشکلی رو من دیدم گفتم اینجا گزارش کنم

![calendar](https://user-images.githubusercontent.com/5570350/62678680-6378c380-b9c7-11e9-9176-822f3e6cd553.png)

همونطور که ملاحظه میفرمایید روز اول ماه دو بار تکرار شده و مشخص نیست کدام روز هفته درسته
</div>

**Comment by babakhani** [comment]
لطفا به نسخه آخر به روز رسانی کنید.

**Comment by esfahanweb** [comment]
@babakhani I'm using "persian-datepicker 1.1.4" with "persian-date 1.1.0", I think both of packages are up to date.

**Comment by babakhani** [comment]
@esfahanweb 
Please update `pwt.datepicker` to v1.2.0
Also you can use npm.
`npm install persian-datepicker@latest`
`npm install persian-date@latest`
Let me know if you have any problem.

**Comment by esfahanweb** [comment]
the bug fixed in v1.2.0
tnx
