### ISSUE TITLE
How to add font icon for next and previous?

### ISSUE THREAD

**Issue by mrmmg** [babakhani/pwt.datepicker#306]
Hi
I want to use font icons like [fontawesome](https://fontawesome.com) or [icomoon](https://icomoon.io/) for styling the calendar but I cannot do this. 
I knew that if use `navigator.text` and `btnNextText` and `btnPrevText` i can make text for next and prev button. now I want to use icon font for these buttons. any example?
thank you

**Comment by Ali-Azmoud** [comment]
وقتی دیت پیکر رو تعریف کردید زیرش این رو بنویسید

```
    $('.pwt-btn-prev').html('<i class="fa fa-chevron-left"></i>');
    $('.pwt-btn-next').html('<i class="fa fa-chevron-right"></i>');
```
