### ISSUE TITLE
بسته شدن منوی انتخاب تاریخ بصورت خودکار

### ISSUE THREAD

**Issue by dadrezaei** [babakhani/pwt.datepicker#307]
در حال حاضر بعد از انتخاب تاریخ، منوی انتخاب تاریخ همچنان باز میمونه و حتما باید یک جایی از صفحه کلیک بشه تا منو بسته بشه. وقتی منو بازه معمولا روی _اینپوت_ بعدی رو میپوشونه و کاربر برای پر کردن _اینپوت_ بعدی مجبوره اول یه جایی از صفحه کلیلک کنه تا منو بسته بشه و بعد بتونه _اینپوت_ بعدی رو پر کنه. اگر بشه با انتخاب تاریخ منو بصورت خودکار بسته بشه کارآیی بیشتری داره.

**Comment by nasserman** [comment]
یک خصوصیت هست به اسم autoClose: true, که اگر اون رو ست کنید بعد از انتخاب تاریخ خودش بسته می شه و نیازی به کلیک نیست
