### ISSUE TITLE
ست کردن تاریخ بصورت سال و ماه مثل1396/01

### ISSUE THREAD

**Issue by pouya75** [babakhani/pwt.datepicker#309]
با سلام و تشکر از کتابخونه کاربردیتون میخواستم تاریخ بصورت تنها سال و ماه نمایش بده این کار انجام شد ولی زمانی که از دیتاپیکر انتخاب بشه ولی برای اولین بار که میخواد نمایش داده بشه یعنی بهش ولیو ست میکنیم باید روز هم ست بشه وگرنه اگه روز نباشه تاریخ روز نمایش داده میشه میخوام ی تاریخ مشخص برای اولین نمایش که صفحه لود میشه بدون روز نمایش داده بشه  چیکار باید بکنم چطور ولیو ست کنم برای اولین بار که نمایش داده میشه که روز نباشه ممنون میشم راهنمایی کنین

**Comment by mort3za** [comment]
سوال واضح نیست.

**Comment by pouya75** [comment]
اون مشکل حل شد سوالی که دارم اگر در فیلد های تاریخ ولیو نزاریم بصورت پیش
فرض تاریخ امروز را نمایش میدهد اگه بخواهیم کاری کنیم که تاریخ یک روز قبل
یعنی دیروز نمایش داده بشه باید چیکار کنیم؟

در تاریخ چهارشنبه ۱۶ اکتبر ۲۰۱۹،‏ ۰:۲۸ Morteza Ziyae <
notifications@github.com> نوشت:

**Comment by mort3za** [comment]
Use this option: http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype  
Live example: https://codepen.io/mort3za/pen/dyyvwYW

**Comment by mort3za** [comment]
Use this option: http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype  
Live example: https://codepen.io/mort3za/pen/dyyvwYW

**Comment by pouya75** [comment]
نه جناب جسارتا به این شکل نه که VALUE از قبل بهش ست کنیم میخوایم بدون اینکه
VALUE داشته باشه تاریخ یک روز قبل ست بشه یعنی به طور مثال امروز 2 ابان 98
هست بدون اینکه ولیو بدیم بصورت پیش فرض بشه 1 ابان تاریخ فردا که 3 ابان هست
بشه 2 ابان بدین شکل

**Comment by mort3za** [comment]
تاریخ دیروز رو تولید کنید و توی اون ولیو ست کنید و بعد دیت‌پیکر رو اینیت کنید.  
تاریخ دیروز رو راحت میشه تولید کرد. 

new persianDate().add('days', -1).format("YYYY-MM-DD")

**Comment by pouya75** [comment]
انجام دادم جناب ولی وقتی تاریخ و عوض میکنم باز میپره به تاریخ دیروز یعنی
تاریخی دیگه کم نمیشه

در تاریخ پنجشنبه ۲۴ اکتبر ۲۰۱۹،‏ ۸:۳۳ Morteza Ziyae <
notifications@github.com> نوشت:

**Comment by mort3za** [comment]
من مشکلی نمی‌بینم، تاریخ رو عوض هم می‌کنم مشکلی نداره  
https://codepen.io/mort3za/pen/vYYmywB

اگه باز مشکلی هست واضح‌تر توضیح بدید

**Comment by pouya75** [comment]
>
> https://codepen.io/pouya7598/pen/jOOLEJJ


من میخوام  tdate یک روز قبل تر نمایش بده برای اولین بار که لود میشه و بشه
تاریخ و تغییر داد ولی اجرا نمیشه ممنون میشم کمک کنین

>
>
