### ISSUE TITLE
تقویم

### ISSUE THREAD

**Issue by nikman360** [babakhani/pwt.datepicker#31]
با سلام و خسته نباشید
آقای باباخانی این تقویمی که طراحی کرده اید بسیار عالی هست.

من به یک مورد در بر خوردم که تا حالا نتوانستم آن را حل کنم.
وقتی تایم پیکر فراخوانی می شود و زمان ذخیره می شود ، هنگامی که دوباره به آن مراجعه می شود(جهت ویرایش) - ساعت حال در تکست باکس قرار می گیرد و ساعتی که ذخیره شده را نمایش نمی دهد
من ابتدا فکر کردم مربوط به فرمت انتخابی هست اما بعد متوجه شدم که هیچ فرمتی را نمایش نمی دهد و زمان حال را نمایش می دهد.

مورد دوم: وقتی تاریخ را ذخیره می کنم که به صورت جلالی ذخیره می شود - برای بار دوم که به آن مراجعه می شود(برای ویرایش)نیاز دارد که تاریخ را به میلادی تبدیل و ذخیره کنیم تا هنگام فراخوانی مجدد تقویم آن را درست نمایش دهد.اگر راهی پیدا کنید که در تکست باکس تقویم را جلالی نمایش و هنگام ذخیره شدن آن را میلادی ذخیره کند بسیار عالی می شود(هماهنگی با پایگاه داده) یا اینکه یک کانفیگ برای انتخاب نوع ورودی (جلالی یا میلادی)در نظر بگیرید بهتر می شود.

اگرازعنوان دیت تایم پیکر برای تقویم استفاده کنید در جستجوی گوگل راحت تر پیدا می شود

مورد بعدی : اگر از بوت راست چین شده استفاده شود جهت های >< هم جابجا می شود

مورد مهم تر اگر برای تقویم یک تارگتی در نظر بگیرید تا وقتی روی دکمه کلیک شد تقویم نمایش داده شود و بعد از انتخاب تاریخ تقویم بسته شود و نتیجه در تکست باکس ذخیره شود.یک نگاهی به تقویم زیر بیندازید

http://eonasdan.github.io/bootstrap-datetimepicker/

از مومنت استفاده کرده

از شما بابت طراحی چنین تقویم خوبی سپاس گذارم و منتظر پاسخ شما هستم

**Comment by babakhani** [comment]
با درود فراوان
مورد اول:حق با شماست و این موضوع در نسخه ای که تا چند روز دیگه منتشر خواهد شد (0.3.7) برطرف می شه
مورد دوم: http://jsfiddle.net/Gm7eM/22/
عنوان دیت تایم پیکر هم پیشنهاد خوبیه به کلمات کلیدی سایت و شاید عنوان اضافه اش می کنم
 در بوت راست چین دیده نشده بود من چک می کنم و این هم در نسخه (0.3.7)  برطرف خواهد شد
مورد آخر هم تو(0.3.8) اضافه خواهد شد .
با سپاس از همکاری و پیشنهادات خوب شما

**Comment by pylover** [comment]
Ishun aghaye babakhani hastand

**Comment by nikman360** [comment]
بله حق با شماست
این هم از مشکلات سریع خوانیه 
آقای باباخانی همچنان در انتظار رفع مشکل دریافت ساعت هستیم

با سپاس

**Comment by parsigold** [comment]
سلام جناب باباخانب
مچکرم از زحماتتون
تقویم شما امکان نمایش دو ما بصورت همزمان رو هم داره؟

**Comment by pylover** [comment]
Please send it as a new issue with the question tag.
