### ISSUE TITLE
سال کبیسه

### ISSUE THREAD

**Issue by alihastam** [babakhani/pwt.datepicker#313]
آقای باباخانی ممنون از پکیجتون
آقای باباخانی سال کبیسه در پکیجتون رعایت شده یا خیر؟ امکانش هست در آینده این آپشن رو اضافه کنید ممنون میشم چون برای پروژه ام واقعا لازم دارم

**Comment by mort3za** [comment]
Yes, it supports the leap years. You can check the date 30-12-1395 in demo.
