### ISSUE TITLE
استفاده بدون jQuery

### ISSUE THREAD

**Issue by abotalebie** [babakhani/pwt.datepicker#317]
من به این اسکریپت به صورت جاوا اسکریپت بدون جی کوئری نیاز دارم.
آیا می تونید این کار رو انجام بدید یا خودم شروع به تبدیل پروژه کنم؟

**Comment by babakhani** [comment]
We have a plan to remove jQuery in next major version that will be released on December 15.

**Comment by mohammadreza99** [comment]
آیا این امکان بوجود اومده؟
من همچنان بدون نصب جیکوئری خطا میگیرم
