### ISSUE TITLE
Disable Specific Date

### ISSUE THREAD

**Issue by Aminvakili** [babakhani/pwt.datepicker#318]
Hi, How to disable Specific date? for example 27 mehr 1398 which is equal to 1571529094201 and we need to disable this date. I know we should use checkDate as a function but how should we call our specific date to be disabled. 
thanks

**Comment by mort3za** [comment]
```
$('.check-date-example').persianDatepicker({
    checkDate: function(unix){
        return ! _.isEqual(new persianDate(unix).toArray().slice(0, 3), [1398, 7, 27])
    }
});
```

`_.isEqual` is a function in lodash that checks the equality of two arrays.

**Comment by mehrankordavani** [comment]
hi @mort3za 
thanks for your solution, can i ask how can i disable more than one disable Specific date?

your answer works for one Specific date. i used '[[1398, 7, 27],[1398, 7, 28]]' instead of '[1398, 7, 27]' for disabling two days but it didn't worked. can you guide please?

**Comment by mort3za** [comment]
@mehrankordavani try defining a date range inside checkDate and check if `unix` is inside that range or not.  
Something like `return unix < mindate || unix > maxdate`  
You can compare Date objects by `<` and `>`

**Comment by mehrankordavani** [comment]
can you make example please for 3 specific dates or more?
 
for example i want to disable 1398/12/24 and 1398/12/27 and 1398/11/5
so how can i disable this  Specific dates on calender  as you said by defining date range?


i have to write like below?
'''' 
$('.check-date-example').persianDatepicker({
    checkDate: function(unix){
        return unix < mindate || unix > maxdate
    }
});
    ''''

**Comment by mehrankordavani** [comment]
hi again, @mort3za  thanks for solution, i did below code for disable 3 specific date and it works. but i do not know its most optimized way or not.
 if i had 20 specific dates this would be huge line of code. 


```
$('.check-date-example').persianDatepicker({
    checkDate: function(unix){
                return ! _.isEqual(new persianDate(unix).toArray().slice(0, 3), [1398, 7, 27]) && ! _.isEqual(new persianDate(unix).toArray().slice(0, 3), [1398, 7, 28])  && ! _.isEqual(new persianDate(unix).toArray().slice(0, 3), [1398, 7, 29])

    }
});

```

is there better way?

**Comment by mort3za** [comment]
Create a list from your disabled dates and use a loop over that list inside checkDate to reduce code size.

**Comment by mehrankordavani** [comment]
@mort3za Thanks.

**Comment by mort3za** [comment]
You're welcome

**Comment by armanzadpour** [comment]
> $('.inline-example').persianDatepicker({
            inline: true,
            altField: '#inlineExampleAlt',
            altFormat: 'LLLL',
            toolbox:{
                calendarSwitch:{
                    enabled: false
                }
            },
            navigator:{
                scroll:{
                    enabled: false
                }
            },
            maxDate: new persianDate().add('month', 12).valueOf(),
            minDate: new persianDate().subtract('month', 12).valueOf(),
            timePicker: {
                enabled: true,
                second: false,
                meridiem: {
                    enabled: true
                }
            }
        });

**Comment by armanzadpour** [comment]
Hi, I want to not allow user to select previous days, my code is like this, please help

`$('.inline-example').persianDatepicker({
            inline: true,
            altField: '#inlineExampleAlt',
            altFormat: 'LLLL',
            toolbox:{
                calendarSwitch:{
                    enabled: false
                }
            },
            navigator:{
                scroll:{
                    enabled: false
                }
            },
            maxDate: new persianDate().add('month', 12).valueOf(),
            minDate: new persianDate().subtract('month', 12).valueOf(),
            timePicker: {
                enabled: true,
                second: false,
                meridiem: {
                    enabled: true
                }
            }
        });`

**Comment by armanzadpour** [comment]
Hi, I want to not allow user to select previous days, my code is like this, please help
`$('.inline-example').persianDatepicker({

 inline: true,
            altField: '#inlineExampleAlt',
            altFormat: 'LLLL',
            toolbox:{
                calendarSwitch:{
                    enabled: false
                }
            },
            navigator:{
                scroll:{
                    enabled: false
                }
            },
            maxDate: new persianDate().add('month', 12).valueOf(),
            minDate: new persianDate().subtract('month', 12).valueOf(),
            timePicker: {
                enabled: true,
                second: false,
                meridiem: {
                    enabled: true
                }
            }
        });`

**Comment by aminvakili** [comment]
@armanzadpour 
For limiting the access of previous days you have to use the "minDate" variable while setting up you calendar. 
here is an example of restricting the available days:
`$('.inline-example').persianDatepicker({
        minDate: new persianDate().add('day', 1).valueOf()
});`

**Comment by armanzadpour** [comment]
@aminvakili thanks bro

**Comment by armanzadpour** [comment]
@aminvakili mate، How to choose the hour and minute between 2 values in the same code?
for example 9:00 to 22:00

**Comment by aminvakili** [comment]
@armanzadpour 
This issue is closed, therefore please consider opening a new issue for your question. 
In there we can discuss it and hopefully find the solution.
