### ISSUE TITLE
Library Problem with WordPress v5.3

### ISSUE THREAD

**Issue by karimi-mohsen** [babakhani/pwt.datepicker#321]
Hi,
persian datepicker library in WordPress 5.3 is having interfering with Javascript's code. The date selector cannot be opened. in The calendar plugin has interfered with the function of the buttons.
But in the previous version of WordPress, no problem.
Please fix the issue and make the necessary compatibility with WordPress 5.3
thank you.

**Comment by babakhani** [comment]
@karimi-mohsen unfortunately at the moment we don't have any plan to that . thank you to take time and report the issue
