### ISSUE TITLE
تغییر فرمت ورودی

### ISSUE THREAD

**Issue by khoshniat** [babakhani/pwt.datepicker#328]
هنگامی که فرمت نمایش رو تغییر میدم صفحه بعد از هربار رفرش شدن تاریخ رو اشتباه نشون میده

```
$('#user-birth_day').persianDatepicker({
            altField: '#user-birth_day_time',
            altFormat: 'X',
            format: 'YYYY/MM/DD',
            observer: false,
            initialValue: false,
        });
```

```
<input type="text" class="form-control" id="user-birth_day"
                     placeholder="تاریخ تولد" name="birth_day">
<input id="user-birth_day_time" hidden name="birth_day_time">
```

![birthday](https://user-images.githubusercontent.com/48559657/74866610-68e89a80-5368-11ea-8b89-065b370f7f5f.PNG)

**Comment by babakhani** [comment]
@khoshniat I created an exmaple on jsfiddle with your code and everything works fine, could reproduce your problem at jsfiddle by forking my example, thanks.
https://jsfiddle.net/babareza/kLpzjg37/
