### ISSUE TITLE
clear persianDatepicker value

### ISSUE THREAD

**Issue by ssabzzz** [babakhani/pwt.datepicker#329]
How can i set datePicker value to null? as far as i can see passing null to setDate() doesn't work.
I can check it being null somehow but I wanted to see if an option comes with persianDatepicker already to do that.
thx.

**Comment by mohammadhzp** [comment]
It's easy, a solution might be to listen to the double click event:

```
$(document).on('dblclick', '.pdate', function () {
        $(this).val('');
});
```
