### ISSUE TITLE
افزودن فانکشن ست کردن تاریخ

### ISSUE THREAD

**Issue by mpourhasan** [babakhani/pwt.datepicker#33]
سلام آقای باباخانی،
تقویم بسیار عالی و کاربردیه و استایل بوت اسرپ هم زیباترش کرده فقط در صورت امکان در هنگام اینیشیالایز تقویم فانکشن ست کردن تاریخ رو هم اضافه کنین.
ممنون

**Comment by alionline759** [comment]
سلام من هم به این فانکشن نیاز دارم خیلی خیلی فوری. میشه بگید کی این اضافه میشه؟

**Comment by babakhani** [comment]
دورد بر دوستان
این مورد در نسخه بعدی اضافه خواهد شد
امیدوارم بتونم تا هفته دیگه نسخه جدید رو منتشر کنم.

**Comment by alisubware** [comment]
با سلام
اگه بتونید زمان تقریبی افزودن این قابلیت رو اعلام کنید ممنون میشم. چون توی یک پروژه بهش احتیاج دارم. و ممکنه مجبور شم از کامپوننت دیکه ای استفاده کنم
با تشکر

**Comment by babakhani** [comment]
درود 
راستش دوست داشتم زودتر انجام بشه.
ولی زمان کافی ندارم.
اما تو تعطیلات نوروز بدون شک انجام خواهد شد.
در حال حاضر اگر عجله دارید نمونه های مشابه خوبی وجود داره.
موفق باشید.
