### ISSUE TITLE
Range Selector does not work properly with time

### ISSUE THREAD

**Issue by ferykhan1362** [babakhani/pwt.datepicker#331]
range selector does not work properly with time!
There seems to be no control over time?
Please help me if there is a solution, thank you

(Something like the link below
[https://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers](url)

**Comment by babakhani** [comment]
@ferykhan1362  There is a range selector [example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#range-selector), although its without time, you can enable timepicker in [config](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configtimepicker-object). also its a good idea to change the example with new one with time support.
