### ISSUE TITLE
persian datepicker : onSelect event not worked in mobile view 

### ISSUE THREAD

**Issue by kianmehr21** [babakhani/pwt.datepicker#332]
onSelect event not worked in mobile touch

**Comment by babakhani** [comment]
@kianmehr21 thanks for report  i will check it

**Comment by mehrna** [comment]
@babakhani Thanks for your cool extension.
By the way I wrote a wrapper on it ([yii2-jalali-datepicker](https://github.com/mrlco/yii2-jalali-datepicker) ) for using on Yii 2 framework. 
I have the same problem as @kianmehr21 mentioned. would you mind if I ask you when will be patched?

**Comment by babakhani** [comment]
@mehrna thank you and good job at `yii2-jalali-datepicker`, i will add a new section to readme to introduce projects like this. and about the bug it wil be fixed at July 1st

**Comment by mehrna** [comment]
> i will add a new section to readme to introduce projects like this.

@babakhani Thank you, it's very kind of you.

> and about the bug it wil be fixed at July 1st

It's a very good news. I'm looking forward to it.

**Comment by mehrna** [comment]
Dear @babakhani,
Any updates on this?

**Comment by mort3za** [comment]
I just tested an example here https://codepen.io/mort3za/pen/rNeemjg  
The onSelect event is logging a message on console.  
Device: Android 9, SM-A730F
Browser: Chrome 84.0.4147.125

![8f605dc8-e3b5-4a88-b903-99f44bcb5ac9](https://user-images.githubusercontent.com/510242/90308938-29ef6800-def9-11ea-882c-6dd7d4b7c867.jpg)

Can you test the pen above on your device and report the result?
