### ISSUE TITLE
jQuery Conflict

### ISSUE THREAD

**Issue by MehranLabour** [babakhani/pwt.datepicker#334]
i have problem with version of pwt.datepicker jquery plugin and other jQuery versions in my page.

ok i did below code solution but not worked for me,

[StackOverflow](https://stackoverflow.com/questions/6332111/jquery-version-conflict)
and i saw this [issue](https://github.com/babakhani/pwt.datepicker/issues/47) and i couldn't understand it or maybe its not possible. 

i tried to define new object of datepicker jQuery like below code 
```
<script type="text/javascript" src="{{ asset('datepicker/jquery/dist/jquery.js') }}"></script>
    <script type="text/javascript">
        var jQuery_3_4_1 = $.noConflict(true);
    </script>
```
then i  use below code for test that this object works or not

```
<script>
        (function($) {
            $('<button>Use jQuery 1.1.3</button>')
                .click(function() {
                    alert('Top: ' + $(this).offset().top + '\n' +
                        'jQuery: ' + $.fn.jquery);
                })
                .appendTo('body');
        })(jQuery_3_4_1);
    </script>

```
and jQuery_3_4_1 works fine to alert me. but i cant this object for  jquery files of datepicker like  "datepicker/js/persian-datepicker.js".

what should i do?is it possible to make it right or not?

**Comment by mort3za** [comment]
datepicker does not include or import jQuery itself, you may use it with your preferred jQuery version.

This conflict is not related to datepicker plugin. I'm going to close this issue but feel free to open it if you still have any question.
