### ISSUE TITLE
persian datepicker to gregorian altfield

### ISSUE THREAD

**Issue by c0d3c0mpl3t3** [babakhani/pwt.datepicker#336]
Hello,
can i choose persian datepicker in init value(1395/10/12) and update to gregorian(2017-1-1) in date alt field?!

**Comment by babakhani** [comment]
Hi, you can do it Please look at this example http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#altfield
and the options document
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configaltformat-string
