### ISSUE TITLE
altFormat: 'gregorian' to gregorian D M Y

### ISSUE THREAD

**Issue by hadimajidi** [babakhani/pwt.datepicker#339]
Dear
Is there any way to get the altFormat: 'gregorian' with gregorian D M Y. Because it always returns in full format like this "Fri Jul 20 1979 00:00:00 GMT+0200 (Central European Summer Time)"

**Comment by babakhani** [comment]
I hope it could help you.
http://babakhani.github.io/PersianWebToolkit/doc/persian-date/#format
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configaltformat-string
