### ISSUE TITLE
Broken resource links upon package upgrade

### ISSUE THREAD

**Issue by Fardinak** [babakhani/pwt.datepicker#34]
You have a great package and I really appreciate that you've published it to bower, but appending the version number to the compiled scripts is not a good practice.
Consider the scenario where a consumer tries to update the package; all the links and configurations need to be updated in that case, which can be simply avoided.

I would also suggest using Require.js to define the package instead of using globals.

**Comment by babakhani** [comment]
I will fix it in next version.
Thanks for your suggestion.

**Comment by pylover** [comment]
It's not good idea, To avoid caching and race condition problems, you have to change the file name on each update.
have you ever seen a javascript library (like jquery & etc ... ) ?

Please take a look at:

http://stackoverflow.com/a/857557/680372
http://www.particletree.com/notebook/automatically-version-your-css-and-javascript-files/
http://discuss.gradle.org/t/what-is-the-best-practice-for-managing-javascript-libraries-such-as-jquery/7579/7

**Comment by Fardinak** [comment]
What @pylover has mentioned is true,

**Comment by Fardinak** [comment]
What @pylover has mentioned is generally true.
Using Require.js would fix both problems though! I strongly recommend it.

**Comment by Fardinak** [comment]
Well, now none of the examples/demos (e.g. http://jsfiddle.net/babareza/DqppC/) are working because of the same issue.
I really think there are better ways to address caching! Nowadays everybody compiles and concatenates scripts on their own; so the library developer needn't worry about it that stuff!

Like I said, event jQuery doesn't do it! ;)

**Comment by babakhani** [comment]
In new 0.5.5 version, I remove version part of plugin file name.
