### ISSUE TITLE
مشکل observe

### ISSUE THREAD

**Issue by amiiiiiink44** [babakhani/pwt.datepicker#341]
سلام 
observe با  کیبرد قسمتnum کار نمیکنه 

و میخام کاری کنم که وقتی سال رو زدم 1399 به طور مثال دیگه بعدش خودش اسلش بندازه تا ماه بزنم و روز....

**Comment by babakhani** [comment]
@amiiiiiink44  I made an example and cant find your issue, please fork this example and create new example to reproduce the problem, feel free to reopen this issue if you do that, thanks
https://jsfiddle.net/babareza/hkqt8fdv/
