### ISSUE TITLE
end date

### ISSUE THREAD

**Issue by hadimajidi** [babakhani/pwt.datepicker#342]
dear
there is no method for the end date. Because it is not very nice to have an inactive date without the ability of selection when there are mandate and max date.
thx

**Comment by babakhani** [comment]
@hadimajidi could you explain more your need, i cant understand your problem.

**Comment by hadimajidi** [comment]
I mean if you set max and min date it just inactivates the rest dates and shows them but in gray. Is there any method to show the all calendar for a specific period just like jquery min and max date?
