### ISSUE TITLE
max or min date for a specific date justlike jquery datepicker

### ISSUE THREAD

**Issue by hadimajidi** [babakhani/pwt.datepicker#343]
On jquery datepicker you are able to set min or max date like this maxDate: '-14Y'. Is there any command like this or we should find the date of 14 years ago and then change it to the Unix mode?

**Comment by mort3za** [comment]
There is no such thing available in the datepicker itself, you can generate your required date by [persianDate](https://github.com/babakhani/PersianDate#add) add('years', -14) or [date-fns](https://date-fns.org/v1.29.0/docs/addYears)
