### ISSUE TITLE
inactive gregorian  date when you set mindate and your setting is persian

### ISSUE THREAD

**Issue by hadimajidi** [babakhani/pwt.datepicker#344]
this is the code
         $(this).pDatepicker({
            observer: true,
            onlySelectOnDate: true,
            maxDate: 1098042653715,
            minDate: (-1223776286000),
            initialValue: false,
            initialValueType: 'gregorian',
            altField: '.altFieldd',
            altFormat: 'gregorian',
            autoClose: true,

            format: 'dddd , DD MMMM  YYYY ',
            format: 'L',
            autoClose: false,
            'toolbox': {
               'submitButton': {
                  'enabled': true,
                  'text': {
                     'fa': 'تایید',
                     'en': 'Submit'
                  }
               }
            }
         })
when you click on the gregorian date all calendar is inactive and non-selectable
any help ?

**Comment by babakhani** [comment]
@hadimajidi 
I made and example, your config makes all days inactive in both mode, please check your `minDate` and `maxDate`,
feel free to fork the fiddle and reproduce your problem and reopen this issue, thanks.
https://jsfiddle.net/babareza/w4xapv6h/
