### ISSUE TITLE
Observer doesn't work when date format is YYYY/MM/DD hh:mm:ss

### ISSUE THREAD

**Issue by alimardani94** [babakhani/pwt.datepicker#345]
my datepicker configuration is shown below, but when i change the input value, the calendar does not change

`
datepickerElem.pDatepicker({
                observer: true,
                altField: '#start',
                altFormat: 'X',
                format: 'YYYY/MM/DD hh:mm:ss',
                responsive: true,
                minDate: new persianDate().valueOf(),
                toolbox: {
                    enabled: true,
                    submitButton: {
                        enabled: true,
                    },
                    calendarSwitch: {
                        enabled: false
                    }
                },
                timePicker: {
                    enabled: true,
                    step: 1,
                },
            });
`

**Comment by mort3za** [comment]
Duplicate of #243
