### ISSUE TITLE
DatePicker does not trigger the change event

### ISSUE THREAD

**Issue by Fardinak** [babakhani/pwt.datepicker#35]
I'm using the component in an angularjs application and the bindings are broken because the component is not firing/triggering neither then `change` nor the `input` event on the element.
I've made a temporary fix by using the `onSelect` callback, but this can be handled better from the source.

If anybody needs it, here's my ngDirective:
```javascript
var linker = function(config) {
  return {
    restict: 'A',
    link: function(scope, element, attrs) {
      config = ng.extend({
        persianDigit: false
      }, config);

      var _onSelect = config.onSelect;
      config.onSelect = function(t) {
        element.trigger('change');
        if(_onSelect) _onSelect.apply(this, arguments);
      };

      element.pDatepicker(config);
    }
  };
};
```

**Comment by babakhani** [comment]
@Fardinak Thanks for share your work. also I will fix it in next version, and move your directive to document.
