### ISSUE TITLE
Double Picker

### ISSUE THREAD

**Issue by msadegh3001** [babakhani/pwt.datepicker#352]
Is any option to use picker in double picker mode ?

**Comment by mort3za** [comment]
Unfortunately it doesn't have such an option.
As an idea, you may want to consider using two different datepickers and update `minDate` and `maxDate` on every picker based on the selected date on the other one.

**Comment by mort3za** [comment]
Updated ⬆️

**Comment by msadegh3001** [comment]
Thanks for your help . Seems have to customize a perfect date picker for my
purpose.
