### ISSUE TITLE
how to disable holidays on date picker for jalali

### ISSUE THREAD

**Issue by ashkankiani** [babakhani/pwt.datepicker#353]
میخوام تعطیلات رسمی توی دیت پیکر غیر فعال بشه
i want to disable holidays in my datepicker

**Comment by mort3za** [comment]
Please check this example: http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate  
You can check if the date is in your holidays list or not, then return true or false in `checkDate` function.
