### ISSUE TITLE
عدم نمایش صحیح سال، وقتی مقدار تکست باکس با فونت انگلیسی پر می شود

### ISSUE THREAD

**Issue by webloper01** [babakhani/pwt.datepicker#354]
اگر مقدار تکست باکسی که دیت پیکر 
به آن متصل است از طریق دیتابیس پر شود و اعداد با فونت انگلیسی باشند، دیت پیکر سال اشتباهی را نمایش میدهد

![DP1](https://user-images.githubusercontent.com/55461845/108881285-61616e80-7618-11eb-9cfc-3990f6e1df3a.jpg)

**Comment by mort3za** [comment]
Font has nothing to do with values. I guess you're passing a wrong date to the field.  
You may want to fork this pen and reproduce your issue, so we can help:  
https://codepen.io/mort3za/pen/oNLvvPw

**Comment by webloper01** [comment]
![DP2](https://user-images.githubusercontent.com/55461845/108898184-25d09f80-762c-11eb-8dcc-483d605a86f8.jpg)

این فیلد های توی دیتابیس هست.
کادر سبز رنگ تاریخی هست که با کاراکترهای فارسی ذخیره شده که این مورد زمان فراخوانی مشکلی ندارد.
کادر قرمز رنگ تاریخی هست که با کاراکترهای انگلیسی ذخیره شده. این مورد زمان فراخوانی سال اشتباه رو نمایش میده.

با توجه به فراخوانی دیتا از دیتابیس، نمیتونم توی 
codepen
فورک کنم

**Comment by mort3za** [comment]
This is a client side plugin. You always can replace backend data with sample data to test client side things.

**Comment by mort3za** [comment]
@BehrouzTorabi  See these examples:  https://codepen.io/mort3za/pen/MWoabYV  

The only difference of them is `initialValueType: 'gregorian',` and `initialValueType: 'persian',`.  
The option you mentioned just changes the language not the type of calendar. Uncomment `"calendar": { "persian": { "locale": "en" } }` in the link above and see the change.

You're always welcome to reopen the issue or create a new one.

**Comment by BehrouzTorabi** [comment]
That's right, my mistake, thanks
