### ISSUE TITLE
There is no way for multiple select 

### ISSUE THREAD

**Issue by VeRJiL** [babakhani/pwt.datepicker#356]
Hi there,

Is there any way to select multiple dates and get the values or let programmers to have access to the selected "td" tag so they can add a custom CSS class?

there is a way to store the selected dates inside an object but there is no way to make a diff for user to understand the dates he has selected

**Comment by babakhani** [comment]
Sorry its not supported by this library, Although you can add this functionality by using library API and some dom manipulation.
