### ISSUE TITLE
فیلتر کردن یک روز خاص هفته

### ISSUE THREAD

**Issue by mohsenmehribusinesss** [babakhani/pwt.datepicker#360]
درود و خسته نباشید جناب باباخانی، تشکر از پکیج عالیتون
آقا من میخام در زمان انتخاب کاربر نتواند روزهای پنجشنبه و جمعه را انتخاب کند، راهی هست آیا ؟ پیشاپیش تشکر

**Comment by firstboy000** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate
