### ISSUE TITLE
how to use this in magento 2 requireJS

### ISSUE THREAD

**Issue by alikhani97** [babakhani/pwt.datepicker#366]
I want to use this persian datepicker on magento which using require.js but after loading dependency I'm getting pwtdatepicker is not defined or persianDate is not a function error!
I used this [links](https://github.com/babakhani/persian-datepicker-next-version/blob/master/demo/js/index.html) sample code for test but not working.

**Comment by babakhani** [comment]
Are you using next version? its under development, there could be some problems. We will going to publish it by November.

**Comment by mirshahreza** [comment]
I have same issue and I use old version not Next version. Are you tested it with require.js?
