### ISSUE TITLE
please add initialvalue with date and time together support

### ISSUE THREAD

**Issue by hrshfa** [babakhani/pwt.datepicker#370]
please add initialvalue with date and time together support
i set value of input to value="1396-05-06 23:45:30" and this is not working.
only i must use date, for example value="1396-05-06"

**Comment by babakhani** [comment]
Its added in next version, https://github.com/babakhani/persian-datepicker-next-version.

**Comment by hrshfa** [comment]
ممنونم از پاسخگوی سریع شما
کد جدیدتون رو هم تست کردم ظاهرا هنوز این مشکل حل نشده است
من تا نوامبر منتظر می مونم تا ان شاءالله نسخه پایانی رو انتشار بدید.
حتما این مورد رو هم لحاظ کنید ممنون از لطف شما بزرگوار
