### ISSUE TITLE
persian calendar with en locale issue

### ISSUE THREAD

**Issue by san4z** [babakhani/pwt.datepicker#371]
the framework i use is Laravel with blade on front end, persian datepicker with locale "en". when the page refreshes from a validation error in a form, the value of date changes to this "779-02-21", but it works fine on "fa" locale.

**Comment by mort3za** [comment]
I guess that's not a bug with this library, it's because of date conversion during refresh in your PHP code.

Anyway, if you think this is a bug please provide a sample code so I can check it. You can use [this template](https://codepen.io/pen?template=oNYPBem) for creating your Pen if you want.

**Comment by san4z** [comment]
thanks, you right, i just need an option or sth to prevent that, i find one eventually. with using this option " initialValueType:'persian' " everything works fine.
