### ISSUE TITLE
فیلتر کردن "چند" روز از هفته

### ISSUE THREAD

**Issue by InsaneSwain** [babakhani/pwt.datepicker#374]
سلام وقت بخیر ، من با متد چک دیت این کار رو میکنم فقط اجازه فیلتر سازی یک روز رو بهم میده ، چجوری چند روز رو فیلتر کنم؟ ممنون
 checkDate: function(unix){
                            return new persianDate(unix).day() != 3;
                        }
مثلا بجای 3 آرایه قبول نمیکنه. ممنون میشم بگید باید چیکار کنم

**Comment by Viper-Bit** [comment]
@InsaneSwain 
```js
checkDate: function(unix) {
    return [1, 2, 3].indexOf(new persianDate(unix).day()) === -1;
}
```
