### ISSUE TITLE
مشکل مقدار داشتن کنترل و تغییر توسط Datepicker 

### ISSUE THREAD

**Issue by aakousha** [babakhani/pwt.datepicker#375]
با عرض سلام
بنده در استفاده از این پلاگین به یک مشکلی بر خورد کردم که وقتی در فایل تست پیوستی هم چک کردم همین مشکل وجود دارد که تصویر آن را به پیوست گذاشتم.
زمانی که DatePicker روی تاریخ شمسی ست شده و کنترلی (input[type="textbox"]) که DatePicker روی آن ست شده دارای مقدار تاریخ شمسی ‌پیش فرض (در فرم های ویرایش) است، وقتی DatePicker باز می‌شود تاریخ شمسی موجود را بعنوان تاریخ میلادی شناخته و در DatePicker آن را کانورت می‌کند به شمسی.
مثلا وقتی مقدار پیش فرض کنترل برابر با 1359/07/01 باشد، DatePicker روی تاریخ 10 تیر سال 738 باز می‌کند.
در صورتی که اگر نوع تقویم را میلادی انتخاب کنیم، دقیقا همان تاریخ 1359/07/01 را نشان می‌دهد ولی از نوع میلادی...
می‌توانید خودتون تست کنید و نتیجه را ببینید.
ممنون میشم راهنمایی ام کنید.
![Untitled](https://user-images.githubusercontent.com/89748645/131264357-acc39f7a-fea6-4218-8d66-c1ca056cb4c3.png)

**Comment by mort3za** [comment]
Check this https://github.com/babakhani/pwt.datepicker/issues/354#issuecomment-907611438
