### ISSUE TITLE
استفاده با وب پک

### ISSUE THREAD

**Issue by RealMrHex** [babakhani/pwt.datepicker#381]
<p dir="rtl">سلام چرا در خصوص استفاده با وب پک هیچ مستنداتی ندارید؟:)
<br>
میشه بفرمایید باید چیکار کرد مثل persian-date بشه از date-picker هم توی وب پک استفاده کرد؟
ممنون</p>

**Comment by mort3za** [comment]
That should work the same way you use jQuery. Just add it as a global or import where you need it.
