### ISSUE TITLE
how to disable specific dates in an array?

### ISSUE THREAD

**Issue by mehrzarrin** [babakhani/pwt.datepicker#382]
how to disable specific dates in an array?

**Comment by mehrzarrin** [comment]
how to disable specific dates in an array?

**Comment by mort3za** [comment]
Please check here: http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate and https://github.com/babakhani/pwt.datepicker/issues/374#issuecomment-907552499
