### ISSUE TITLE
نصب در لاراول

### ISSUE THREAD

**Issue by pejmanazagh1995** [babakhani/pwt.datepicker#394]
سلام ،برای استفاده از این پکیج بسیار مفید شما در پروژ لاراول خود به مشکل خوردم 
همونجور که توی داکیومنت گفته شده اول با استفاده از npm install persian-datepicker  نصب کردم 
بعد <head>
  <link rel="stylesheet" href="css/persian.datepicker.css"/>
  <script src="js/jquery.js"></script>
  <script src="js/persian.date.js"></script>
  <script src="js/persian.datepicker.js"></script>
</head>
را به هدر صفحه اضاف کردم
وبعد            
<input type="text" class="example1" /> 
این input را داخل فرم گذاشتم و
فایل جاوا اسکریپت را نوشتم                                                                                                                                                
<script type="text/javascript">
  $(document).ready(function() {
    $(".example1").pDatepicker();
  });
</script>

ولی در کل کار نمیکند
و اینکه اگر از پروژه در مرورگر view source بزنم 
این فایل ها هرگز شناخته نمیشوند
لطفا راهنمایی کنید
ممنون

**Comment by mort3za** [comment]
Please ask it in a Laravel community. That's not related to this package.
