### ISSUE TITLE
مشکل جلوگیری از انتخاب تاریخ اینده 

### ISSUE THREAD

**Issue by sadeghghanbaridev** [babakhani/pwt.datepicker#395]
درود بر شما 
بنده هنگام استفاده از مقدار  
    maxDate: new persianDate().unix()
کل روزهای انتخابی غیر فعال می شود 
مشکل از کد نویسی منه یا افزونه باگ داره
 با تشکر

**Comment by mort3za** [comment]
You may use `new Date().getTime()` or `new persianDate().unix() * 1000`

**Comment by sadeghghanbaridev** [comment]
ممنون برطرف شد 
ولی داخل داکیومنتتون نبود اگه امکانش هست بزارید
