### ISSUE TITLE
Wrong value

### ISSUE THREAD

**Issue by alidehghan** [babakhani/pwt.datepicker#4]
Hello Reza,

Whenever a Persian date is set in the text-box, it doesn't recognize it properly and display wrong date... I think you assumed given date should be in Gregorian Date while I need to set it in Jalalian-Date. I guess it is better to provide a config or in smart way detect intelligently given value is persian or gregorian...

By the way, this behavior is not included in previous version.

Also I attached a screenshot of this error.

Thanks for your efforts :)

![image](https://f.cloud.github.com/assets/3834767/1090219/9d578c90-1652-11e3-9796-8e6d229eabe4.png)

**Comment by aghict** [comment]
Hello,
I have this problem, 
How can I fix it?
