### ISSUE TITLE
عدم ارسال ارقام فارسی به بک اند

### ISSUE THREAD

**Issue by amindeist** [babakhani/pwt.datepicker#401]
در سمت فرانت هنگام انتخاب تاریخ ارقام به شکل فارسی هستند و به همون شکل هم به بک اند ارسال میشن
راهی هست بشه این رفتار ‌‌‌‌‌‌‌پیشفر
ض دیتپیکر را تغییر داد

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by amin3d** [comment]
سلام، اول اینو یک جای کدت اضافه کن::
```
String.prototype.toEnglishDigits = function() {
    return this.replace(/[۰-۹]/g, function(chr) {
        var persian = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
        return persian.indexOf(chr);
    });
};
```
بعدش توی option ها در تابع onSelect این کد را اضافه کن.
```
            $(".date").pDatepicker({
                autoClose: true,
                format: 'YYYY/MM/DD',
                onSelect: function (params) {
                  valOf = $(this.model.inputElement).val();
                  $(this.model.inputElement).val(valOf.toEnglishDigits());
               }
                
            });

```
