### ISSUE TITLE
عدم کارکرد در وردپرس

### ISSUE THREAD

**Issue by fullstack1995** [babakhani/pwt.datepicker#402]
سلام وقت بخیر
تقویم در وردپرس کار نمیکند و خطای extend میدهد
https://s6.uupload.ir/files/untitled_y17s.png
بخش لود فایل ها در هوک
```
add_action( 'admin_enqueue_scripts', function()
{
    // styles
    wp_enqueue_style( 'wcoe-persian-datepicker.min', WCOMB_URL . 'assets/admin/css/persian-datepicker.min.css' );

    // scripts
    wp_enqueue_script( 'wcoe-persian-date.min', WCOMB_URL . 'assets/admin/js/persian-date.min.js', ['jquery'] );

    wp_enqueue_script( 'wcoe-persian-datepicker.min', WCOMB_URL . 'assets/admin/js/persian-datepicker.min.js', ['wcoe-persian-date.min'] );

    wp_enqueue_script( 'wcoe-default', WCOMB_URL . 'assets/admin/js/default.js', [ 'wcoe-persian-datepicker.min'] );
} );
```

محتوای فایل default.js
```
(function($) 
{
    $( document ).ready( function()
    {
        $( '.normal-example' ).persianDatepicker( {
            initialValue: false,
            format: 'YYYY/MM/DD',
            calendar:{
                persian: {
                    locale: 'en'
                }
            }
        });
    } )

})(jQuery);
```

**Comment by mansoursaleh69** [comment]
سلام. منم همین مشکل رو دارم. لطفا اعلام نتیجه کنید

**Comment by seramo** [comment]
دوستانی که این مشکل رو روی وردپرس یا نسخه های جدید جی کوئری دارند ابتدا و انتهای کدهای persian-datepicker.js یا نسخه minify شده اضافه کنند:
```
jQuery( function($) {
    // Original Code
});
```
تا مشکل بخش هایی که از $ استفاده شده رفع بشه

**Comment by mansoursaleh69** [comment]
> دوستانی که این مشکل رو روی وردپرس یا نسخه های جدید جی کوئری دارند ابتدا و انتهای کدهای persian-datepicker.js یا نسخه minify شده اضافه کنند:
> 
> ```
> jQuery( function($) {
>     // Original Code
> });
> ```
> 
> تا مشکل بخش هایی که از $ استفاده شده رفع بشه

سلام مهندس جان. تشکر بابت پاسخ. مشکل حل شد
