### ISSUE TITLE
The setDate Method works incorrectly !!

### ISSUE THREAD

**Issue by mohamadz14** [babakhani/pwt.datepicker#41]
there is a problem with setDate Method in your calendar ..
for example when i use the : $("#example1" ).pDatepicker("setDate","2015,12,24,11,11" );

the input text shows the date : 772-11-14 12:42:48 PM date !!

**Comment by babakhani** [comment]
Hi
As can be seen in document currently this method accept persian date array, dot.net date format, unix date and javascript date object.
something like : [1391,12,3,12,11]
your string input "2015,12,24,11,11" is not parsable to persian date library.

**Comment by mohamadz14** [comment]
i have tested both persian and gregorian dates , and the problem exists in both dates !

**Comment by babakhani** [comment]
You must define date as Array not as a string.
