### ISSUE TITLE
FR: set input value

### ISSUE THREAD

**Issue by omidp** [babakhani/pwt.datepicker#43]
I want to set input element value as null on page load. by default it will be set to the current date.

**Comment by svfnix** [comment]
با سلام
منم این مشکل رو داشتم 
مجبور شدم یه دستی تو کد ببرم
لاین ۲۱۸۳
 _updateInputElement: function () {
        var self = this;
        self._flagSelfManipulate = true;
        // Update Alt Field
        self.altField.val(self.altFieldFormatter(self.state.selected.unixDate)).trigger('change');
        ;
        // Update Display Field
        var val = self.inputElem.val();
        if(val == 0 && !this._viewed)
    	{
        	//self.inputElem.val('').trigger('change');
    	}
        else
    	{
            self.inputElem.val(self.formatter(self.state.selected.unixDate)).trigger('change');   	
    	}
    
        ;
        self._flagSelfManipulate = false;
        return self;
    },

**Comment by ImanMh** [comment]
there is a setDate method explained in the documentations. You can use it to set any initial date you want.

**Comment by javansolo** [comment]
با سلام
بنده هم این مشکل رو دارم گاهی نیاز دارم به صورت پیش فرض اطلاعات داخش خالی باشه و بعد کاربر انتخاب کنه
و یا از دیتا بیش مقدار خالی قرار بدم
لطفا این مورد را برطرف کنید متشکر می شوم

**Comment by javansolo** [comment]
تابع
_updateInputElement:
به این صورت تغییر دهید تو فایل کم حجم   min
_updateInputElement:function(){var e=this;return e._flagSelfManipulate=!0,e.altField.val(e.altFieldFormatter(e.state.selected.unixDate)).trigger("change"),(e.inputElem.val() && !e._viewed) ? e.inputElem.val('').trigger('change') : e.inputElem.val(e.formatter(e.state.selected.unixDate)).trigger("change"),e._flagSelfManipulate=!1,e}
درست میشه

**Comment by zfarhad** [comment]
+1

**Comment by babakhani** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/#apisetdateunix
