### ISSUE TITLE
error in setDate method

### ISSUE THREAD

**Issue by gowhari** [babakhani/pwt.datepicker#45]
`setDate` method make changes correctly but `setDate` calls `this.setTime()`. In `setTime` method, `this.timePicker.setTime` is undefined. Seems that `this.timePicker` is the config object not `ClassTimePicker` object.

I called setDate as this: `$('.selector').pDatepicker('setDate', [1393,1,1])`

**Comment by babakhani** [comment]
Hi
Thank you for taking the time to submit an issue.
I fixed it in "Develop" branch. 
Currently you must use "Develop" branch until release 0.5.0

https://github.com/babakhani/pwt.datepicker/tree/Develop

good luck.
