### ISSUE TITLE
datepicker string date input bug solution.

### ISSUE THREAD

**Issue by sattariam** [babakhani/pwt.datepicker#52]

**Comment by sattariam** [comment]
این روش اشکال داشت بستمش

**Comment by babakhani** [comment]
درود
دوست عزیز اگر روش درستی پیدا کردید و خواستید کد شما به پروژه اضافه بشه قبل از هر چیز لینک زیر رو بررسی کنید تا بتونیم این 
قبیل کارهارو از بهترین راه انجام بدیم. سپاس

https://guides.github.com/activities/contributing-to-open-source/
