### ISSUE TITLE
setTime method throwing error

### ISSUE THREAD

**Issue by ImanMh** [babakhani/pwt.datepicker#53]
I'm doing this: 

``` javascript
  $(".example1").
    pDatepicker().
    pDatepicker("setDate",[1333,3,3,3,3] ).
    pDatepicker( "show" );
```

And I see this error: 
Uncaught TypeError: this.timePicker.setTime is not a function    ClassDatepicker.setTime @ persian-datepicker-0.4.5.js:2229

**Comment by repper** [comment]
I also got the same error, please fix it in the next release. Thanks
Solution would be simple like 'if(this.timePicker.setTime)' before calling the method.
