### ISSUE TITLE
add method

### ISSUE THREAD

**Issue by javadbat** [babakhani/pwt.datepicker#57]
can you add method we can get current selected date in it like:
$(datepicker selection).getSelectedDate();
and add keyboard navigation to it we can use arrow key

**Comment by babakhani** [comment]
New version is under development.
this feature added in new version.
you can see last document and examples in this link:
[http://babakhani.github.io/PersianWebToolkit/beta/datepicker/](http://babakhani.github.io/PersianWebToolkit/beta/datepicker/)
also you can use last beta version by 
`npm i persian-datepicker@beta`
