### ISSUE TITLE
do not initialize Input element with current date

### ISSUE THREAD

**Issue by nicmon** [babakhani/pwt.datepicker#61]
The Element will be initially filled with current date which makes it impossible to show a Label as Placeholder in it. Please add a setting to control this behavior.

**Comment by babakhani** [comment]
Hi
Thank you for taking the time to submit an issue.

**Comment by ImanMh** [comment]
+1
You can select your input and manually set the ```.val('')``` to an empty value for now.

**Comment by mehranRasulian** [comment]
+1 for fix this issue.

**Comment by babakhani** [comment]
from 0.5.5 you can set `initialValue` false and date-picker leave inputs empty until user select date.
