### ISSUE TITLE
How to use in angular js

### ISSUE THREAD

**Issue by uxitten** [babakhani/pwt.datepicker#62]
بابت پلاگینی که نوشتید تشکر میکنم خیلی جالب بود فقط یک موردی را دوست داشتم لحاظ کنید

وقتی چند مورد از این پلاگین در صفحه داریم با یک ایدی از هم متمایز بشن که بتونیم به شی خود پلاگین دسترسی داشته باشیم
مثلا در هنگام تعریف  پلاگین این ایدی ست کنیم 

 angular.element(id).persianDatepicker({
                                    id:'persianDatepicker1'
                                    format: "HH:mm:ss",
                                    onlyTimePicker: true
                                });

 angular.element(id).persianDatepicker({
                                    id:'persianDatepicker2'
                                    format: "HH:mm:ss",
                                    onlyTimePicker: true
                                });

![capture](https://cloud.githubusercontent.com/assets/1549069/11554544/dfcd7ada-9990-11e5-8f03-a0bcf10420d3.PNG)

**Comment by babakhani** [comment]
درود
سپاس از اینکه این گزار ش رو ثبت کردید.
در نسخه بعدی این مورد ابر طرف خواهد شد.

**Comment by babakhani** [comment]
you must use directive for using datepicker in angular.

**Comment by kambizzandi** [comment]
دوست عزیز میشه لطفا عنوان این issue رو تغییر بدید؟
من تو لیست با دیدن عنوان «سلام» هیچ چیزی رو نتونستم پیش بینی کنم و مجبور شدم بازش کنم.
