### ISSUE TITLE
TimePicker bug when disabling showMeridian

### ISSUE THREAD

**Issue by ahmadazimi** [babakhani/pwt.datepicker#63]
Hi there,

I've found a bug in the code. When you enable `timePicker` and set `showMeridian: false` you can not switch between PM and AM hours.

I've read our code and found the problem is placed in `ClassTimePicker` class:
In `_movehour` method of this class, you checked the `currentVal >= 12` and then reset the `this.hourStep` to `this.hourStep`.

Is there anyway to fix this?

**Comment by babakhani** [comment]
Hi
Thank you for taking the time to submit an issue. I fix it as soon as possible in the next version 0.5.0
