### ISSUE TITLE
Jalali date initial value!

### ISSUE THREAD

**Issue by khadem** [babakhani/pwt.datepicker#64]
سلام
سپاس فراوان بابت زحمات شما
وقتی در فرم تاریخ شمسی را یک فیلد به صورت پیش فرض نمایش می دهم 
datepicker
آنرا میلادی فرض می کند و دوباره تبدیلش می کند.
در نتیجه بجای تاریخ روز مثلا: 
773/07/07
نمایش داده می شود
چطور باید تنظیم شود که تاریخ اولیه را هم شمسی در نظر بگیرد و این تبدیل را انجام ندهد؟
لطفا راهنمایی بفرمایید

**Comment by babakhani** [comment]
در نسخه فعلی باید تاریخ پیش فرض را با فرمت میلادی وارد نمایید
موفق باشید

**Comment by darkoob12** [comment]
سلام
ممنون از اینکه کدتون رو اشتراک گذاشتین.
این مشکل برا من در ریفرش کردن صفحه پیش میاد.
یعنی بار اول تارخ درسته بعد هر بار که ریفرش می کنم 622 تا از سال کم میشه...
اگه ctrl+ f5 بزنم درست میشه
چطوری باید تاریخ پیشفرض رو ست کنم؟

**Comment by eafshary** [comment]
سلام
تاریخ حتی اگه میلادی هم باشه تو مرورگر فایرفاکس بازهم این مشکل وجود دارد!!!
خوب اگه تاریخ شمسی بشه به عنوان پیش فرض گذاشت خیلی بهتره که!!!

**Comment by z-avanes** [comment]
سلام
آقای @babakhani 
مرسی از زحماتی که برای پلاگین خوبتون کشیدین 
لطفا اگر امکانش هست یک متغییر تعریف کنید که بشه آدرس تایپ دیفالت رو تغییر داد 
با تشکر

**Comment by babakhani** [comment]
@z-avanes  @khadem 
درود فراوان بر شما
در این اولین فرصت این امکان اضافه خواهد شد

**Comment by hramezani** [comment]
PR #159

**Comment by babakhani** [comment]
with thanks to  @hramezani , after version 1.0.0 we have "intialValueType" that accept 'persian', 'gregorian'.

see [example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype)

**Comment by pouya75** [comment]
سلام تشکر بابت کتاب خونه کاربردیتون  یسوال داشتم میخوام تاریخ بصورت تنها سال و ماه نمایش داده بشه این کارو انجام دادم و از یک تاریخ مشخص شروع بشه و تاریخ روز نمایش داده نشه برای همین وقتی میخوام مقدار اولیه داخل اینپوت ست کنم حتما باید روز هم ست بشه راهی هست که مقدار اولیه از یک تاریخ دیگه مثلا 1396/02 شروع بشه یعنی توی مقدار اولیه هم اینطور ست بشه ونمایش داده بشه
