### ISSUE TITLE
force empty initial value

### ISSUE THREAD

**Issue by z-avanes** [babakhani/pwt.datepicker#66]
hi 
thx for great works!
how can force datepicker initiate with empty value in input tag and after user select date from datepicker then value replace?

**Comment by babakhani** [comment]
Hi
Unfortunately, currently this option dosnt exist.
I implement this in 0.5.0.

**Comment by z-avanes** [comment]
thx 
i will wait for new version

**Comment by z-avanes** [comment]
i try to find in source code where initial value insert but i am confused
we have many .val in source
please help me find place of geanarator code

**Comment by hramezani** [comment]
[pull request](https://github.com/babakhani/pwt.datepicker/pull/69).
