### ISSUE TITLE
'triggerIfChanged' of undefined

### ISSUE THREAD

**Issue by Cloze** [babakhani/pwt.datepicker#68]
سلام وقت بخیر

ظاهرا یک اشکالی در یک جایی وجود داره که باعث میشه در هنگام انتخاب تاریخ خطاهایی رخ بده 

Uncaught TypeError: Cannot read property 'triggerIfChanged' of undefined
Uncaught TypeError: Cannot read property 'msie' of undefined
Uncaught TypeError: Cannot read property 'msie' of undefined

این خطاها الان توی سایت نمونه هم وجود داره 

منظورم اینجاست :
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/0.4.5/

**Comment by rSafari** [comment]
طبق چکی که من کردم این مشکل فقط در 
Google Chrome Canary 50  رخ میده
یعنی فقط تو نسخه development اینجوریه و در کروم معمولی مشکلی نیست

**Comment by babakhani** [comment]
درود این مشکل رو بررسی و در نسخه بعدی رفع خواهیم کرد.
با سپاس از گزارش شما

**Comment by babakhani** [comment]
@Cloze This issue fixed in version 1.0.0
let me know if you still have an issue.
