### ISSUE TITLE
مشکل ماه فروردین 95

### ISSUE THREAD

**Issue by payamomrani** [babakhani/pwt.datepicker#70]
سلام
ممنون بابت پلاگین بسیار عالیتون
یه مشکلی که وجود داره ، مشکل ماه فروردین 95 که اسفند 94 درج میشه
لطفا پیگیری کنید

**Comment by isondev** [comment]
برای من اوکی هست شما چه مرورگری استفاده می کنید؟ تاریخ سیستم رو هم چک کنید.

**Comment by payamomrani** [comment]
در حال حاضر برای بنده هم درست نمایش میده
احتمالا درستش کردن یا اینکه ماه تغییر پیدا کرده و درست شده

**Comment by babakhani** [comment]
درود بر دوستان
اگر دوباره با این مشکل مواجه شدین لطفا گزارش کنید 
در حال حاضر با توجه به اینکه من نمی تونم این مشکل رو ببینم کاری از دستم بر نمی یاد
