### ISSUE TITLE
Range Selector

### ISSUE THREAD

**Issue by saeedvaziry** [babakhani/pwt.datepicker#72]
سلام.
ببخشید چجوری میشه انتخاب چندگانه تاریخ داشته باشیم؟

**Comment by babakhani** [comment]
در حال حاضر این امکان وجود نداره. امیدوارم در نسخه های بعد اضافه اش کنیم

**Comment by babakhani** [comment]
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#range-selector
