### ISSUE TITLE
Datepicker Default value

### ISSUE THREAD

**Issue by alinasiri1367** [babakhani/pwt.datepicker#74]
Hi
How can we set default value set?

**Comment by elhampour** [comment]
Did you find answer for this ? How can we set default time to null

**Comment by elhampour** [comment]
The solution ( if i can call it ) i found is that after the creation of input , i simply change the value to whatever i want ( in my case null value ) .

`$(".datetimepicker").val("");`

**Comment by p3ym4n** [comment]
🙏 but i think it really needs to get the formatted date from predefined value . 
the solution i have find is not good and ro mokhame 😕

**Comment by vahid-jml** [comment]
hi 
you can use val() function before and after persianDatepicker function and set observer to true
val = element.val();
	jQelement.persianDatepicker({
	format: DateFormat,
	observer: true,
	autoClose : true,
})
element.val(val);

**Comment by zfarhad** [comment]
+1

**Comment by omidnikrah** [comment]
@vahid-jml hi
i write your code but only change date in date field and not change in datePicker
![image](https://cloud.githubusercontent.com/assets/8777948/25034818/976e9624-20fe-11e7-9cbf-5a135f63e7c3.png)
what should I do?

**Comment by OmidAhmadyani** [comment]
i set $('mylelement').val('1398/02/02');
it init default value but i have @vahid-jml  problem and didnt set in calender.
please fix it.
i prefer write a function for set default value

**Comment by OmidAhmadyani** [comment]
> 
> 
> @vahid-jml hi
> i write your code but only change date in date field and not change in datePicker
> ![image](https://cloud.githubusercontent.com/assets/8777948/25034818/976e9624-20fe-11e7-9cbf-5a135f63e7c3.png)
> what should I do?

hi i resolve this problem
you should write you code such as

var pd = $('.selector').persianDatepicker();
pd.setDate(1382276091100)

http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/#apisetdateunix

**Comment by javaditco** [comment]
> > @vahid-jml hi
> > i write your code but only change date in date field and not change in datePicker
> > ![image](https://cloud.githubusercontent.com/assets/8777948/25034818/976e9624-20fe-11e7-9cbf-5a135f63e7c3.png)
> > what should I do?
> 
> hi i resolve this problem
> you should write you code such as
> 
> var pd = $('.selector').persianDatepicker();
> pd.setDate(1382276091100)
> 
> http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/#apisetdateunix

Thanks a lot, it works.

**Comment by moslem68** [comment]
> > > @vahid-jml hi
> > > i write your code but only change date in date field and not change in datePicker
> > > ![image](https://cloud.githubusercontent.com/assets/8777948/25034818/976e9624-20fe-11e7-9cbf-5a135f63e7c3.png)
> > > what should I do?
> > 
> > 
> > hi i resolve this problem
> > you should write you code such as
> > var pd = $('.selector').persianDatepicker();
> > pd.setDate(1382276091100)
> > http://babakhani.github.io/PersianWebToolkit/doc/datepicker/api/#apisetdateunix
> 
> Thanks a lot, it works. But how to generate this number. It isn't Timestamp, I checked it.
> I found it. It is a javascript Timestamp, which is in mili-second.

use this code:
            pd.setDate(new persianDate([1400, 4, 17]));
