### ISSUE TITLE
auto filling inputs

### ISSUE THREAD

**Issue by nasserghiasi** [babakhani/pwt.datepicker#75]
often developer don't need to auto-fill inputs by today date. this lib don't have an option for disabling this feature.

**Comment by p3ym4n** [comment]
i think the present solution is to make it empty by js.

**Comment by nasserghiasi** [comment]
I think this is bad feature or is a bug.

**Comment by babakhani** [comment]
@nasserghiasi  This is a missed feature and i will try to fix this in next version.  You can also contribute and help make pwt.datepicker better.

**Comment by p3ym4n** [comment]
i love to.
i try a little but i couldn't 😕.
maybe i can do it with some help or wait for your next version 😃.

**Comment by nasserghiasi** [comment]
thank you, I'll try to help you.
