### ISSUE TITLE
set calendar to gregorian type 

### ISSUE THREAD

**Issue by miladmeidanshahi** [babakhani/pwt.datepicker#76]
hi how can i change type of cal to gregorian ? or it it any way to something like toggle or switch between jalali and gregorian type in calendar dropdown ?

many thx

**Comment by babakhani** [comment]
Currently this options dosent exist. in next version maybe. Thanks for your report.

**Comment by babakhani** [comment]
Gregorian calendar added in version 1.0.0
[Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#gregorian-calendar)
