### ISSUE TITLE
disable specific days...

### ISSUE THREAD

**Issue by saeedvaziry** [babakhani/pwt.datepicker#77]
i want to disable specific days... minDate and maxDate not helped...!

**Comment by babakhani** [comment]
Currently this options dosent exist. in next version maybe. Thanks for your report.

**Comment by saeedvaziry** [comment]
i would love it...

**Comment by hramezani** [comment]
[PR](https://github.com/babakhani/pwt.datepicker/pull/104)

**Comment by babakhani** [comment]
@hramezani  thank you for your effort, after 0.5.5 and refactor code to es6, I add `checkDate` config. you can see example [here](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#checkdate).
