### ISSUE TITLE
مشکل در دریافت timestamp

### ISSUE THREAD

**Issue by milad145** [babakhani/pwt.datepicker#79]
آیا امکان تغییر دادن مقدار 
altField
نیز وجود دارد؟
برای مثال بتوان بر هزار تقسیم کرد تا زمان را برحسب ثانیه به دست آورد نه میلی ثانیه !
با تشکر

**Comment by babakhani** [comment]
این مثال رو نگاه کنید
http://jsfiddle.net/Gm7eM/38/
و همچنین این بخش رو
http://babakhani.github.io/PersianWebToolkit/doc/persiandate/#/displaying/format/

**Comment by milad145** [comment]
ممنون
