### ISSUE TITLE
how set null date

### ISSUE THREAD

**Issue by sfarbod** [babakhani/pwt.datepicker#80]
با عرض سلام و خسته نباشید
تقویم جالبی هست ولی متاسفانه هر چه تلاش کردم که تاریخ پیش فرض بتونم خالی تنظیم کنم موفق نشدم.
در بعضی مواقع در برنامه تاریخ خالی هست و بعد از انتخاب کاربر باید پر شود
لطفا راهنمایی بفرمایید نحوه استفاده من اشتباه هست یا اشکال از تقویم هست.
با تشکر فربد

**Comment by amirfahmideh** [comment]
سلام من هم همین مشکل رو برای شروع استفاده از این تقویم خوب دارم

**Comment by kambizzandi** [comment]
مهندس به داد این قسمت هم برس.
اینکه تو فرم ها آیتم هایی داشته باشیم که اجباری نباشن که طبیعیه (آره؟)
پس لطفا این موضوع رو انجام بدین که از نون شب هم واجب تره ;)
جدای از همه اینا واقعا خسته نباشین. کار خوب و تمیزی انجام دادین.

**Comment by jsKamran** [comment]
منم همینطور . الو مهندس کجایی کمک .

**Comment by babakhani** [comment]
@jsKamran 
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/options/#configinitialvalue-boolean
```
{
    initialValue: false
}
```
