### ISSUE TITLE
Don't show datepicker after close that

### ISSUE THREAD

**Issue by hosseinGanjyar** [babakhani/pwt.datepicker#83]
If **'autoclose: true'** After select a date from **datepicke** don't open that again.
Notice: After close **datepicke** focus is over '#fromDate' and no click out of input. So if click over input, see no don't open **datepicke**.

My code:

```
$(document).ready(function () {
        $('#fromDate').persianDatepicker({
            format: 'YYYY/MM/DD',
            autoClose: true
        });
    });
```

`<input id="fromDate" type="text">`

**Comment by mbasirati** [comment]
I have this problem too!

**Comment by mbasirati** [comment]
I solved this issue. I added below code after line 1982 in regular js script `persian-datepicker-0.4.5.js`:
`
if (self.autoClose) {
    self.element.main.hide();
    **$('input').blur();**

}
`

**Comment by hosseinGanjyar** [comment]
Yes, That's work. Thanks for answer
