### ISSUE TITLE
Issue with Positioning

### ISSUE THREAD

**Issue by mamos98** [babakhani/pwt.datepicker#85]
Hi,
First of all, thank for your great work on both Persian Date and Date Picker Libraries.
I recently used them both and found an issue with the positioning of the date picker. The problem is that if you use it inside a Modal (Bootstrap in my case) aside from the fact that I have to manually set the z-index value, it will have some issues.

Since it gets appended to the Body tag, and it has absolute position using in a modal causes some problems like when you scroll the modal date picker tries to stay at its place and believe me, it's devastating. 

All of this issues can be fixed by appending date picker to input parent instead of body and giving it a relative position.

One more thing that happens is that it won't position relative to the input offset. I mean it should realise if there's enough space below the input or not, to open the date picker above or below the input. :)

I will try to fix these issues and once I succeed I will fork your repo, and make a pull request. But in the meantime I will appreciate it if you fix these issues. :open_hands:

**Comment by babakhani** [comment]
HI @mamos98 
We add this as an option in next version, that allow to set date-picker container manually.
Good luck.
