### ISSUE TITLE
مشکل در ست کردن تاریخ با observer  و altField

### ISSUE THREAD

**Issue by ImanDeveloper** [babakhani/pwt.datepicker#87]
با سلام 
تشکر از آقای باباخانی بابت پلاگین
مشکلی که بنده دارم وقتیه که
observer 
و 
altField
رو ست میکنم برای پلاگین
در موقعی که به حالت 
inline 
هست وقتی تاریخی انتخاب میشه روی اینپوت ست میشه و مشکلی هم نیست ولی اگه از طریق جاوا اسکریپت مقداری رو توی اینپوت ست میکنم روی پلاگین ست نمیشه و تاریخ امروز رو نشون میده 
در صورتی که اگه من به صورت دستی همون مقدار رو توی اینپوت ست کنم تغییرات اعمال میشه و تاریخ مربوطه انتخاب میشه

در کل هدف از این کار اینه که وقتی به صورت 
inline 
از پلاگین استفاده میکنم میخوام هم از متد 
setDate
استفاده کنم و هم براش تنظیمات 
maxDate, mindate, onSelect
رو ست کنم.

ممنون میشم اگه راهنمایی بفرمایین.

**Comment by babakhani** [comment]
شما می تونید از امکان زیر استفاده کنید.

$( ".selector" ).pDatepicker("setDate",[1392,12,1,11,11] );
