### ISSUE TITLE
A bug at display Date : Display wrong date after refresh (F5)

### ISSUE THREAD

**Issue by saarraa** [babakhani/pwt.datepicker#88]
Hi Dear friend.
This is a good plugin . thank you for that.
But there is a problem : 
After refresh browser with F5 button , plugin display wrong Date , like :  774-04-21
And then with push Ctrl+F5 , display right date.
I think this problem is because of browser cash. 
How could i correct that ?
Thank you.

**Comment by miladganjali** [comment]
Same Problem here! 
Thanks for this awesome plugin

**Comment by kamyar64** [comment]
Hi Guys
I correct this problem
just turn off autocomplete of your Date textbox

`<input id="persianDate" name="persianDate"  autocomplete="off" type="text">`

**Comment by ElnazIghani** [comment]
این راه حل فقط باعث میشه تاریخ نامتبر نمایش داده نشه. اما آیا خود دیت پیکر هنگام نمایش داده تاریخ های معتبر رو برای انتخاب کاربر نمایش میده؟

**Comment by babakhani** [comment]
if you set the value of input as solar date, this issue will appear. make sure you set the initial value of input as a gregorian date format.

**Comment by hpx70** [comment]
thanks for your awesome work
I am using Gregorian dates and there is no problem.
But, whenever there is a validation error when posting the form, it repopulates the form with old user inputs, and it passes the Shamsi date to date picker, which causes it to produce wrong dates
like 774-04-21

**Comment by ElnazIghani** [comment]
Use a server-side date convertor in the input tag's value attribute.
for example:
` <input asp-for="BirthDate" type="text" class="date-time-picker"
                                   value="@(PersianDateTime.GetMiladiDate(Model.BirthDate??PersianDateTime.GetPersianDate(DateTime.Now).ToString()))">`

**Comment by babakhani** [comment]
@ElnazIghani  thanks a lot.
I close this issue.
see more [Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/)
