### ISSUE TITLE
نادرست بودن timestamp برگردونده شده

### ISSUE THREAD

**Issue by farhadkb6868** [babakhani/pwt.datepicker#90]
با سلام
با تشکر از پلاگین خوبی که تهیه کردید یه اشکال داشتم که می خواستم خدمتتون عرض کنم.
من در جاوا اسکریپت برای دریافت 
timstamp
تاریخ انتخاب شده به این صورت عمل کردم:

```
$("#date-picker").pDatepicker({
onSelect: function (unix_timestamp) {

}
});
```

اما timstamp برگردونده شده خیلی بزرگه و از زمان فعلی خیلی بیشتره.
من با استفاده از تابع setdate تاریخ فعلی رو به زمانی که می خوام تغییر دادم ولی 
و ساعت سیستم من هم درسته اما
timestamp های برگردونده شده توسط onSelect خیلی دور تر اززمانی فعلی هست.
ممنون از وقتی که می ذارید بابت پاسخ گویی

**Comment by babakhani** [comment]
به نظرم این مشکل از وجود میلی ثانیه ها ست
چنانچه مثال زیر رو اجرا کنید می بینید که تاریخ انتخاب شده با تاریخ درج شده در لاگ یکسان است

$("#date-picker").pDatepicker({
onSelect: function (unix) {
    console.log(new pDate(unix).format())
}
});
