### ISSUE TITLE
issue detecting the datepicker object .datepicker-plot-area element

### ISSUE THREAD

**Issue by p3ym4n** [babakhani/pwt.datepicker#91]
hi, 
I have figured out when I change my dom nodes with ajax, the `<div class="datepicker-plot-area">...</div>` divs at the end of body still remains and if there were any related selector or something else to link them to the datepicker object I can use that for removing them , but they all have only a datepicker-plot-area class .
thanks for your help and tell me if I'm wrong.

**Comment by babakhani** [comment]
this issue fixed in 0.5.5
