### ISSUE TITLE
24-clock system

### ISSUE THREAD

**Issue by Tarighi** [babakhani/pwt.datepicker#95]
با سلام و درود وخسته نباشید
ابزار بسیار خوبیه ولی یه کاستی داره
اونم اینه که اگر من بخوام ساعت رو به صورت 24 ساعته انتخاب کنم مجبورم تایپ کنم. 
لطفا امکان نمایش و انتخاب ساعت رو در قالب 24 فراهم کنید. 
با سپاس

**Comment by babakhani** [comment]
جناب طریقی عزیز این مورد در نسخه های آینده اضافه خواهد شد
شاد باشید

**Comment by ElnazIghani** [comment]
با سلام
آیا همچنان در تقویم ایجاد شده قابلیت استفاده از فرمت 24 ساعته وجود ندارد؟
در بین آپشن های موجود تنها می توان توسط
showMeridian: false
قبل و بعداز ظهر را حذف کرد، اما در شرایطی که امکان نمایش 24 ساعته در
plot area
وجود نداشته باشد، در برخی کاربردها، عملا با مشکل مواجه می شویم
با تشکر

**Comment by salehmosleh** [comment]
با سلام و تشكر بابت زحمات شما
پلاگين بسيار خوب و كاربردي و زيبا و داراي طراحي هنرمندانه است ، اما متاسفانه تا فرمت 24 ساعته نداشته باشد تعامل ما با كاربراي ايراني و ديتابيس خودمون يذره پيچيده ميشه. لطفا اين قابليت رو اضافه كنيد. ممنون از شما

**Comment by babakhani** [comment]
@salehmosleh thanks for take your time to fix this issue,
please check new 0.5.5 version.
