### ISSUE TITLE
calendar don't work with predefined value

### ISSUE THREAD

**Issue by nasserghiasi** [babakhani/pwt.datepicker#96]
When I put custom value in date input calendar like 1395/08/25 it get confused and it displaying this value:
773/11/21
why calendar don't have custom date value ability?

**Comment by nasserghiasi** [comment]
seriously?! anybody in there?

**Comment by babakhani** [comment]
Hi
Currently initialize date only accept gregorian date like 02-16-2012 and unix timestamp.
I wish implement this to accept both persian and gregorian date for initialize date.
