### ISSUE TITLE
package.json Error

### ISSUE THREAD

**Issue by ali32b** [babakhani/pwt.datepicker#97]
سلام
فکر میکنم محتوای فایل پکیجتون مشکل دارد وقتی از گولپ یا وبپک استفاده میکنم خطای زیر را دریافت میکنم
0:39] Starting 'webpack'...
{ [Error: ./resources/assets/js/admin/app.js
Module not found: Error: Can't resolve 'persian-datepicker' in '/home/vagrant/Code/ArduinoPanel/resources/assets/js/admin'
resolve 'persian-datepicker' in '/home/vagrant/Code/ArduinoPanel/resources/assets/js/admin'
  Parsed request is a module
  using description file: /home/vagrant/Code/ArduinoPanel/package.json (relative path: ./resources/assets/js/admin)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/vagrant/Code/ArduinoPanel/package.json (relative path: ./resources/assets/js/admin)
    resolve as module
      /home/vagrant/Code/node_modules doesn't exist or is not a directory
      /home/vagrant/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /home/vagrant/Code/ArduinoPanel/resources/assets/js/node_modules doesn't exist or is not a directory
      /home/vagrant/Code/ArduinoPanel/resources/assets/js/admin/node_modules doesn't exist or is not a directory
      /home/vagrant/Code/ArduinoPanel/resources/assets/node_modules doesn't exist or is not a directory
      /home/vagrant/Code/ArduinoPanel/resources/node_modules doesn't exist or is not a directory
      looking for modules in /home/vagrant/Code/ArduinoPanel/node_modules
        using description file: /home/vagrant/Code/ArduinoPanel/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/vagrant/Code/ArduinoPanel/package.json (relative path: ./node_modules)
          using description file: /home/vagrant/Code/ArduinoPanel/node_modules/persian-datepicker/package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/vagrant/Code/ArduinoPanel/node_modules/persian-datepicker is not a file
            .js
              Field 'browser' doesn't contain a vvagrant@homestead:~/Code/ArduinoPanel$ ^C

**Comment by babakhani** [comment]
i will check it.

**Comment by babakhani** [comment]
try new version 0.5.5

**Comment by PouyaAklion** [comment]
when I use  laravel mix to import your package I got an error 
Uncaught Error: Cannot find module "persian-datepicker"
