### ISSUE TITLE
مشکل در استفاده از TimePicker

### ISSUE THREAD

**Issue by Saadeghi66** [babakhani/pwt.datepicker#98]
با سلام و درود وخسته نباشید
ابزار بسیار خوبیه 
اگه لطف کنین و بگین به چه شکل میشه از TimePicker استفاده کرد
به نحوی که با دیتابیس sync باشه ممنون میشم ازتون
من الان از همان تابع setDate برای ست کردن زمان استفاده کردم 
 $("#StoreMorningClose").persianDatepicker({
                altField: '#StoreMorningClose',
                onlyTimePicker: true,
                observer: true,
                format: 'HH:mm',
                timePicker: {
                    enabled: true,
                    scrollEnabled: true,
                    showSeconds: false,
                    minuteStep: 1,
                    hourStep: 1
                },

            });
            $('#StoreMorningClose').pDatepicker("setTime", [parseInt(MorningCloseValue[0]), parseInt(MorningCloseValue[1])]);
با سپاس

**Comment by Saadeghi66** [comment]
مشکلم در نحوه استفاده از دیت پیکر  در زمان خواندن ساعت از دیتابیس هست.نمی دونم از چه تابعی باید استفاده کنم

**Comment by babakhani** [comment]
دوست عزیز شما برای خواندن ساعت از دیتا بیس کافی است تاریخ را با فرمت درست به روی کلاینت ارسال کنید.
به عنوان مثال این جا رو ببین
http://www.unixtimestamp.com/
